param(
    [string]$SourceDir = "D:\zPython\MakerAi\Source"
)

# Spanish words that indicate a comment needs translation (not in typical English code comments)
$spanishIndicators = @(
    'acción', 'acá', 'agregados', 'ahí', 'ahora', 'allí', 'al', 'aquí', 'aunque', 'automáticamente',
    'bandera', 'base', 'bloque', 'bloqueo', 'buscar', 'cadena', 'cambio', 'campo', 'caracteres',
    'clase', 'código', 'comentario', 'como', 'comprobar', 'con', 'convierte', 'correr', 'creado',
    'cuando', 'cuerpo', 'cuenta', 'da', 'datos', 'de', 'debe', 'debería', 'demás', 'dentro',
    'desde', 'después', 'devuelve', 'día', 'días', 'donde', 'durante', 'ejecuta', 'ejemplo',
    'el', 'ella', 'ellas', 'ellos', 'en', 'entonces', 'equipo', 'es', 'ese', 'eso', 'esta',
    'está', 'estado', 'estas', 'estos', 'et', 'evitando', 'fin', 'fue', 'función', 'guía',
    'hasta', 'hijo', 'hijos', 'hacer', 'hay', 'incluye', 'indica', 'información', 'inicio',
    'interno', 'la', 'las', 'le', 'les', 'lista', 'llamada', 'lleno', 'lo', 'los', 'luego',
    'más', 'manera', 'mayor', 'me', 'memoria', 'menor', 'mensaje', 'mientras', 'mismo', 'modificar',
    'modo', 'muchos', 'muy', 'nada', 'necesario', 'ningún', 'no', 'nombre', 'nos', 'nuestra',
    'nuestras', 'nuestros', 'nuevo', 'nueva', 'nuevas', 'o', 'otra', 'otras', 'otro', 'otros',
    'para', 'parte', 'pasos', 'paso', 'pequeño', 'pero', 'pocos', 'poder', 'por', 'porque',
    'puede', 'pueden', 'punto', 'qué', 'que', 'realizar', 'recibe', 'referencia', 'relación',
    'relleno', 'resto', 'retorna', 'se', 'segundo', 'segundos', 'según', 'ser', 'si', 'sí',
    'siempre', 'sin', 'sistema', 'sobre', 'solo', 'solamente', 'su', 'sus', 'también',
    'tamaño', 'tanto', 'tarjeta', 'te', 'tiene', 'tipo', 'todavía', 'todo', 'todos',
    'toma', 'total', 'trabaja', 'través', 'último', 'un', 'una', 'uno', 'unos', 'usas',
    'usa', 'usando', 'utiliza', 'utilizado', 'valor', 'varios', 'vez', 'veces', 'ver',
    'versión', 'ya', 'yo', 'grande', 'hace', 'hecho', 'hechos', 'leer', 'escribir',
    'propio', 'propia', 'propios', 'propias', 'cierto', 'cierta', 'ciertos', 'ciertas',
    'algún', 'alguna', 'algunos', 'algunas', 'ningún', 'ninguna', 'ningunos', 'ningunas',
    'mismo', 'misma', 'mismos', 'mismas', 'otro', 'otra', 'otros', 'otras',
    'primer', 'primera', 'primeros', 'primeras', 'último', 'última', 'últimos', 'últimas',
    'tal', 'tales', 'cual', 'cuales', 'quien', 'quienes', 'donde', 'como', 'cuando',
    'cuanto', 'cuanta', 'cuantos', 'cuantas',
    'aquí', 'ahí', 'allí', 'acá', 'allá', 'cerca', 'lejos',
    'antes', 'después', 'durante', 'mientras', 'luego', 'entonces',
    'arriba', 'abajo', 'dentro', 'fuera', 'encima', 'debajo', 'delante', 'detrás',
    'bien', 'mal', 'mejor', 'peor', 'muy', 'más', 'menos', 'bastante', 'demasiado',
    'poco', 'mucho', 'todo', 'nada', 'algo', 'alguien', 'nadie',
    'este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas',
    'aquel', 'aquella', 'aquellos', 'aquellas',
    'mi', 'mis', 'tu', 'tus', 'su', 'sus', 'nuestro', 'nuestra', 'nuestros', 'nuestras',
    'vuestro', 'vuestra', 'vuestros', 'vuestras',
    'él', 'ella', 'ello', 'ellos', 'ellas', 'nosotros', 'nosotras', 'vosotros', 'vosotras',
    'yo', 'tú', 'él', 'ella', 'usted', 'nosotros', 'vosotros', 'ellos', 'ellas', 'ustedes',
    'me', 'te', 'se', 'nos', 'os', 'lo', 'la', 'le', 'los', 'las', 'les',
    'conmigo', 'contigo', 'consigo',
    'hacer', 'hago', 'haces', 'hace', 'hacemos', 'hacen',
    'decir', 'digo', 'dices', 'dice', 'decimos', 'dicen',
    'poder', 'puedo', 'puedes', 'puede', 'podemos', 'pueden',
    'dar', 'doy', 'das', 'da', 'damos', 'dan',
    'saber', 'sé', 'sabes', 'sabe', 'sabemos', 'saben',
    'querer', 'quiero', 'quieres', 'quiere', 'queremos', 'quieren',
    'llegar', 'llego', 'llegas', 'llega', 'llegamos', 'llegan',
    'pasar', 'paso', 'pasas', 'pasa', 'pasamos', 'pasan',
    'deber', 'debo', 'debes', 'debe', 'debemos', 'deben',
    'tener', 'tengo', 'tienes', 'tiene', 'tenemos', 'tienen',
    'llevar', 'llevo', 'llevas', 'lleva', 'llevamos', 'llevan',
    'dejar', 'dejo', 'dejas', 'deja', 'dejamos', 'dejan',
    'seguir', 'sigo', 'sigues', 'sigue', 'seguimos', 'siguen',
    'encontrar', 'encuentro', 'encuentras', 'encuentra', 'encontramos', 'encuentran',
    'llamar', 'llamo', 'llamas', 'llama', 'llamamos', 'llaman',
    'venir', 'vengo', 'vienes', 'viene', 'venimos', 'vienen',
    'volver', 'vuelvo', 'vuelves', 'vuelve', 'volvemos', 'vuelven',
    'salir', 'salgo', 'sales', 'sale', 'salimos', 'salen',
    'ver', 'veo', 'ves', 've', 'vemos', 'ven',
    'dar', 'doy', 'das', 'da', 'damos', 'dan',
    'saber', 'sé', 'sabes', 'sabe', 'sabemos', 'saben',
    'pensar', 'pienso', 'piensas', 'piensa', 'pensamos', 'piensan',
    'sentir', 'siento', 'sientes', 'siente', 'sentimos', 'sienten',
    'creer', 'creo', 'crees', 'cree', 'creemos', 'creen',
    'conocer', 'conozco', 'conoces', 'conoce', 'conocemos', 'conocen',
    'querer', 'quiero', 'quieres', 'quiere', 'queremos', 'quieren',
    'comenzar', 'comienzo', 'comienzas', 'comienza', 'comenzamos', 'comienzan',
    'entender', 'entiendo', 'entiendes', 'entiende', 'entendemos', 'entienden',
    'recordar', 'recuerdo', 'recuerdas', 'recuerda', 'recordamos', 'recuerdan',
    'importar', 'importo', 'importas', 'importa', 'importamos', 'importan',
    'gustar', 'gusto', 'gustas', 'gusta', 'gustamos', 'gustan',
    'parecer', 'parezco', 'pareces', 'parece', 'parecemos', 'parecen',
    'quedar', 'quedo', 'quedas', 'queda', 'quedamos', 'quedan',
    'tratar', 'trato', 'tratas', 'trata', 'tratamos', 'tratan',
    'contar', 'cuento', 'cuentas', 'cuenta', 'contamos', 'cuentan',
    'existir', 'existo', 'existes', 'existe', 'existimos', 'existen',
    'ocurrir', 'ocurre', 'ocurres', 'ocurre', 'ocurrimos', 'ocurren',
    'servir', 'sirvo', 'sirves', 'sirve', 'servimos', 'sirven',
    'afectar', 'afecto', 'afectas', 'afecta', 'afectamos', 'afectan',
    'representar', 'represento', 'representas', 'representa', 'representamos', 'representan',
    'formar', 'formo', 'formas', 'forma', 'formamos', 'forman',
    'constar', 'consto', 'constas', 'consta', 'constamos', 'constan',
    'corresponder', 'correspondo', 'correspondes', 'corresponde', 'correspondemos', 'corresponden',
    'correspondiente', 'correspondientes',
    'respectivo', 'respectiva', 'respectivos', 'respectivas',
    'siguiente', 'siguientes', 'anterior', 'anteriores',
    'presente', 'presentes', 'futuro', 'futuros', 'pasado', 'pasados',
    'actual', 'actuales', 'nuevo', 'nueva', 'nuevos', 'nuevas', 'viejo', 'vieja', 'viejos', 'viejas',
    'mayor', 'menor', 'mejor', 'peor', 'superior', 'inferior',
    'principal', 'principales', 'secundario', 'secundaria', 'secundarios', 'secundarias',
    'general', 'generales', 'especial', 'especiales', 'particular', 'particulares',
    'común', 'comunes', 'único', 'única', 'únicos', 'únicas',
    'diferente', 'diferentes', 'igual', 'iguales', 'distinto', 'distinta', 'distintos', 'distintas',
    'similar', 'similares', 'semejante', 'semejantes',
    'cierto', 'cierta', 'ciertos', 'ciertas', 'verdadero', 'verdadera', 'verdaderos', 'verdaderas',
    'falso', 'falsa', 'falsos', 'falsas', 'correcto', 'correcta', 'correctos', 'correctas',
    'incorrecto', 'incorrecta', 'incorrectos', 'incorrectas',
    'válido', 'válida', 'válidos', 'válidas', 'inválido', 'inválida', 'inválidos', 'inválidas',
    'necesario', 'necesaria', 'necesarios', 'necesarias', 'innecesario', 'innecesaria', 'innecesarios', 'innecesarias',
    'posible', 'posibles', 'imposible', 'imposibles',
    'probable', 'probables', 'improbable', 'improbables',
    'seguro', 'segura', 'seguros', 'seguras', 'inseguro', 'insegura', 'inseguros', 'inseguras',
    'claro', 'clara', 'claros', 'claras', 'oscuro', 'oscura', 'oscuros', 'oscuras',
    'simple', 'simples', 'complejo', 'compleja', 'complejos', 'complejas',
    'fácil', 'fáciles', 'difícil', 'difíciles',
    'rápido', 'rápida', 'rápidos', 'rápidas', 'lento', 'lenta', 'lentos', 'lentas',
    'grande', 'grandes', 'pequeño', 'pequeña', 'pequeños', 'pequeñas',
    'alto', 'alta', 'altos', 'altas', 'bajo', 'baja', 'bajos', 'bajas',
    'largo', 'larga', 'largos', 'largas', 'corto', 'corta', 'cortos', 'cortas',
    'ancho', 'ancha', 'anchos', 'anchas', 'estrecho', 'estrecha', 'estrechos', 'estrechas',
    'profundo', 'profunda', 'profundos', 'profundas',
    'fuerte', 'fuertes', 'débil', 'débiles',
    'lleno', 'llena', 'llenos', 'llenas', 'vacío', 'vacía', 'vacíos', 'vacías',
    'abierto', 'abierta', 'abiertos', 'abiertas', 'cerrado', 'cerrada', 'cerrados', 'cerradas',
    'libre', 'libres', 'ocupado', 'ocupada', 'ocupados', 'ocupadas',
    'disponible', 'disponibles', 'no disponible',
    'activo', 'activa', 'activos', 'activas', 'inactivo', 'inactiva', 'inactivos', 'inactivas',
    'visible', 'visibles', 'invisible', 'invisibles',
    'público', 'pública', 'públicos', 'públicas', 'privado', 'privada', 'privados', 'privadas',
    'protegido', 'protegida', 'protegidos', 'protegidas',
    'estático', 'estática', 'estáticos', 'estáticas', 'dinámico', 'dinámica', 'dinámicos', 'dinámicas',
    'constante', 'constantes', 'variable', 'variables',
    'local', 'locales', 'global', 'globales',
    'externo', 'externa', 'externos', 'externas', 'interno', 'interna', 'internos', 'internas',
    'propio', 'propia', 'propios', 'propias', 'ajeno', 'ajena', 'ajenos', 'ajenas',
    'mismo', 'misma', 'mismos', 'mismas', 'otro', 'otra', 'otros', 'otras',
    'cada', 'todo', 'toda', 'todos', 'todas', 'ambos', 'ambas',
    'varios', 'varias', 'algunos', 'algunas', 'ningunos', 'ningunas',
    'mucho', 'mucha', 'muchos', 'muchas', 'poco', 'poca', 'pocos', 'pocas',
    'bastante', 'demasiado', 'demasiada', 'demasiados', 'demasiadas',
    'suficiente', 'suficientes', 'insuficiente', 'insuficientes',
    'medio', 'media', 'medios', 'medias', 'completo', 'completa', 'completos', 'completas',
    'parcial', 'parciales', 'total', 'totales',
    'mitad', 'doble', 'triple', 'cuádruple',
    'primero', 'primera', 'primeros', 'primeras', 'último', 'última', 'últimos', 'últimas',
    'siguiente', 'siguientes', 'anterior', 'anteriores',
    'presente', 'presentes', 'pasado', 'pasados', 'futuro', 'futuros',
    'actual', 'actuales', 'nuevo', 'nueva', 'nuevos', 'nuevas', 'antiguo', 'antigua', 'antiguos', 'antiguas',
    'moderno', 'moderna', 'modernos', 'modernas', 'viejo', 'vieja', 'viejos', 'viejas',
    'joven', 'jóvenes', 'adulto', 'adulta', 'adultos', 'adultas',
    'mayor', 'menor', 'mejor', 'peor',
    'superior', 'inferior', 'central', 'laterales',
    'izquierdo', 'izquierda', 'izquierdos', 'izquierdas',
    'derecho', 'derecha', 'derechos', 'derechas',
    'norte', 'sur', 'este', 'oeste',
    'oriental', 'occidental', 'septentrional', 'meridional',
    'aquí', 'ahí', 'allí', 'acá', 'allá',
    'cerca', 'lejos', 'dentro', 'fuera', 'encima', 'debajo',
    'delante', 'detrás', 'alrededor', 'a través',
    'arriba', 'abajo', 'adelante', 'atrás',
    'hoy', 'ayer', 'mañana', 'ahora', 'entonces', 'luego', 'después', 'antes',
    'siempre', 'nunca', 'jamás', 'a veces', 'a menudo', 'rara vez',
    'pronto', 'tarde', 'temprano', 'todavía', 'ya', 'recién',
    'inmediatamente', 'directamente', 'lentamente', 'rápidamente',
    'fácilmente', 'difícilmente', 'simplemente', 'realmente', 'verdaderamente',
    'probablemente', 'posiblemente', 'seguramente', 'ciertamente',
    'efectivamente', 'exactamente', 'precisamente', 'especialmente',
    'principalmente', 'generalmente', 'particularmente', 'específicamente',
    'aproximadamente', 'alrededor', 'casi', 'apenas', 'solamente', 'únicamente',
    'incluso', 'también', 'tampoco', 'además', 'sin embargo', 'no obstante',
    'por lo tanto', 'por eso', 'por lo que', 'así que', 'entonces',
    'pero', 'sino', 'aunque', 'mientras', 'cuando', 'donde', 'como', 'que', 'cual',
    'quien', 'quienes', 'cuyo', 'cuya', 'cuyos', 'cuyas',
    'qué', 'cuál', 'cuáles', 'quién', 'quiénes', 'cuánto', 'cuánta', 'cuántos', 'cuántas',
    'dónde', 'cuándo', 'cómo', 'por qué', 'para qué',
    'este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas',
    'aquel', 'aquella', 'aquellos', 'aquellas',
    'lo', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'el', 'la', 'los', 'las',
    'al', 'del', 'con', 'sin', 'por', 'para', 'de', 'desde', 'hasta', 'sobre', 'bajo',
    'entre', 'contra', 'hacia', 'según', 'durante', 'mediante', 'tras', 'vía',
    'y', 'e', 'ni', 'o', 'u',
    'no', 'sí', 'quizás', 'tal vez', 'acaso',
    'hola', 'adiós', 'gracias', 'por favor', 'perdón', 'disculpa',
    'bien', 'mal', 'mejor', 'peor',
    'casa', 'cosa', 'vez', 'veces', 'día', 'días', 'año', 'años',
    'hora', 'horas', 'minuto', 'minutos', 'segundo', 'segundos',
    'manera', 'forma', 'modo', 'estilo', 'tipo', 'clase', 'categoría',
    'parte', 'lugar', 'sitio', 'posición', 'punto', 'lado',
    'grupo', 'equipo', 'conjunto', 'sistema', 'estructura', 'organización',
    'programa', 'proyecto', 'plan', 'proceso', 'método', 'técnica',
    'problema', 'cuestión', 'asunto', 'tema', 'punto', 'caso',
    'ejemplo', 'modelo', 'patrón', 'estándar', 'norma', 'regla',
    'código', 'texto', 'documento', 'archivo', 'registro',
    'información', 'dato', 'datos', 'contenido', 'mensaje',
    'número', 'cantidad', 'medida', 'tamaño', 'peso', 'distancia',
    'tiempo', 'espacio', 'materia', 'energía', 'fuerza', 'poder',
    'trabajo', 'función', 'tarea', 'actividad', 'operación', 'acción',
    'servicio', 'producto', 'resultado', 'efecto', 'consecuencia',
    'causa', 'razón', 'motivo', 'propósito', 'objetivo', 'meta',
    'idea', 'concepto', 'noción', 'teoría', 'hipótesis', 'suposición',
    'opinión', 'punto de vista', 'perspectiva', 'enfoque', 'posición',
    'situación', 'estado', 'condición', 'circunstancia', 'contexto',
    'nivel', 'grado', 'etapa', 'fase', 'paso', 'etapa',
    'área', 'zona', 'región', 'sector', 'campo', 'dominio', 'ámbito',
    'aspecto', 'elemento', 'componente', 'factor', 'característica',
    'detalle', 'pormenor', 'particularidad', 'especificación',
    'definición', 'descripción', 'explicación', 'interpretación',
    'análisis', 'síntesis', 'evaluación', 'valoración', 'estimación',
    'cálculo', 'medición', 'comparación', 'contraste', 'diferencia',
    'semejanza', 'relación', 'conexión', 'vínculo', 'asociación',
    'comunicación', 'intercambio', 'transferencia', 'transmisión',
    'entrada', 'salida', 'proceso', 'transformación', 'conversión',
    'creación', 'desarrollo', 'construcción', 'producción', 'generación',
    'diseño', 'implementación', 'ejecución', 'realización', 'aplicación',
    'instalación', 'configuración', 'personalización', 'adaptación',
    'modificación', 'actualización', 'mejora', 'optimización', 'ajuste',
    'reparación', 'corrección', 'solución', 'resolución', 'respuesta',
    'pregunta', 'consulta', 'búsqueda', 'exploración', 'investigación',
    'estudio', 'investigación', 'análisis', 'revisión', 'inspección',
    'verificación', 'comprobación', 'validación', 'confirmación',
    'prueba', 'ensayo', 'experimento', 'test', 'evaluación',
    'control', 'supervisión', 'monitoreo', 'seguimiento', 'rastreo',
    'gestión', 'administración', 'dirección', 'liderazgo', 'mando',
    'organización', 'planificación', 'programación', 'coordinación',
    'cooperación', 'colaboración', 'participación', 'contribución',
    'comunicación', 'información', 'notificación', 'anuncio', 'aviso',
    'mensaje', 'señal', 'indicación', 'instrucción', 'orden', 'comando',
    'petición', 'solicitud', 'demanda', 'requerimiento', 'necesidad',
    'requerimiento', 'requisito', 'condición', 'exigencia', 'obligación',
    'permiso', 'autorización', 'licencia', 'aprobación', 'consentimiento',
    'rechazo', 'denegación', 'negativa', 'prohibición', 'vetar',
    'aceptación', 'admisión', 'recepción', 'acogida', 'bienvenida',
    'inicio', 'comienzo', 'principio', 'arranque', 'apertura',
    'fin', 'final', 'término', 'conclusión', 'cierre', 'terminación',
    'continuación', 'seguimiento', 'prosecución', 'prolongación',
    'interrupción', 'pausa', 'suspensión', 'detención', 'parada',
    'reanudación', 'retorno', 'vuelta', 'regreso', 'regreso',
    'cambio', 'modificación', 'alteración', 'transformación', 'variación',
    'movimiento', 'desplazamiento', 'traslado', 'transporte', 'traslado',
    'avance', 'progreso', 'desarrollo', 'evolución', 'mejora',
    'retroceso', 'regresión', 'involución', 'deterioro', 'empeoramiento',
    'éxito', 'fracaso', 'triunfo', 'derrota', 'victoria', 'derrota',
    'logro', 'consecución', 'alcance', 'meta', 'objetivo', 'propósito',
    'intención', 'finalidad', 'sentido', 'significado', 'importancia',
    'valor', 'precio', 'costo', 'gasto', 'inversión', 'presupuesto',
    'beneficio', 'ganancia', 'pérdida', 'daño', 'perjuicio', 'prejuicio',
    'riesgo', 'peligro', 'amenaza', 'incertidumbre', 'incertidumbre',
    'seguridad', 'protección', 'defensa', 'resguardo', 'amparo',
    'confianza', 'seguridad', 'certeza', 'convicción', 'creencia',
    'duda', 'incertidumbre', 'inseguridad', 'desconfianza', 'sospecha',
    'conocimiento', 'saber', 'ciencia', 'sabiduría', 'erudición',
    'experiencia', 'práctica', 'habilidad', 'destreza', 'capacidad',
    'competencia', 'aptitud', 'talento', 'dote', 'don', 'cualidad',
    'propiedad', 'atributo', 'característica', 'rasgo', 'signo', 'síntoma',
    'indicador', 'señal', 'marca', 'huella', 'rastro', 'vestigio',
    'evidencia', 'prueba', 'testimonio', 'demostración', 'confirmación',
    'origen', 'fuente', 'procedencia', 'causa', 'motivo', 'razón',
    'destino', 'meta', 'fin', 'objetivo', 'propósito', 'intención',
    'camino', 'ruta', 'vía', 'sendero', 'trayecto', 'recorrido',
    'viaje', 'travesía', 'excursión', 'paseo', 'gira', 'tour',
    'llegada', 'partida', 'salida', 'regreso', 'vuelta', 'retorno',
    'visita', 'tour', 'recorrido', 'inspección', 'revisión', 'control',
    'reunión', 'encuentro', 'cita', 'conferencia', 'congreso', 'convención',
    'sesión', 'jornada', 'acto', 'ceremonia', 'evento', 'acontecimiento',
    'suceso', 'hecho', 'ocurrencia', 'caso', 'situación', 'circunstancia',
    'momento', 'instante', 'segundo', 'minuto', 'hora', 'día', 'semana',
    'mes', 'año', 'década', 'siglo', 'milenio', 'eternidad',
    'pasado', 'presente', 'futuro', 'ayer', 'hoy', 'mañana',
    'semana', 'fin de semana', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo',
    'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
    'primavera', 'verano', 'otoño', 'invierno',
    'familia', 'padre', 'madre', 'hijo', 'hija', 'hermano', 'hermana',
    'abuelo', 'abuela', 'nieto', 'nieta', 'tío', 'tía', 'primo', 'prima',
    'esposo', 'esposa', 'marido', 'mujer', 'pareja', 'compañero', 'compañera',
    'amigo', 'amiga', 'conocido', 'conocida', 'vecino', 'vecina',
    'persona', 'gente', 'individuo', 'sujeto', 'ciudadano', 'habitante',
    'hombre', 'mujer', 'niño', 'niña', 'joven', 'adulto', 'anciano', 'anciana',
    'población', 'comunidad', 'sociedad', 'grupo', 'colectivo', 'pueblo', 'nación',
    'país', 'estado', 'gobierno', 'administración', 'autoridad', 'poder',
    'política', 'economía', 'social', 'cultural', 'educativo', 'sanitario',
    'público', 'privado', 'estatal', 'nacional', 'internacional', 'regional', 'local',
    'empresa', 'compañía', 'sociedad', 'organización', 'institución', 'entidad',
    'negocio', 'comercio', 'industria', 'sector', 'mercado', 'mercado',
    'cliente', 'usuario', 'consumidor', 'proveedor', 'distribuidor', 'vendedor',
    'producto', 'servicio', 'marca', 'modelo', 'tipo', 'versión', 'variante',
    'calidad', 'cantidad', 'precio', 'valor', 'costo', 'gasto', 'presupuesto',
    'dinero', 'moneda', 'divisa', 'capital', 'fondo', 'inversión', 'crédito',
    'pago', 'cobro', 'deuda', 'impuesto', 'tasa', 'tarifa', 'cuota', 'comisión',
    'cuenta', 'factura', 'recibo', 'ticket', 'boleto', 'entrada', 'billete',
    'documento', 'papel', 'formulario', 'impreso', 'cuestionario', 'encuesta',
    'informe', 'reporte', 'memoria', 'estudio', 'análisis', 'evaluación',
    'proyecto', 'plan', 'programa', 'propuesta', 'iniciativa', 'medida',
    'ley', 'norma', 'regla', 'reglamento', 'ordenanza', 'decreto', 'resolución',
    'derecho', 'obligación', 'deber', 'responsabilidad', 'competencia', 'atribución',
    'permiso', 'licencia', 'autorización', 'aprobación', 'consentimiento', 'visto bueno',
    'contrato', 'acuerdo', 'convenio', 'pacto', 'tratado', 'alianza', 'coalición',
    'guerra', 'paz', 'conflicto', 'disputa', 'controversia', 'polémica', 'debate',
    'discusión', 'conversación', 'diálogo', 'charla', 'plática', 'entrevista',
    'palabra', 'término', 'vocablo', 'expresión', 'frase', 'oración', 'texto',
    'lenguaje', 'idioma', 'lengua', 'habla', 'dialecto', 'jerga', 'argot',
    'comunicación', 'información', 'noticia', 'novedad', 'aviso', 'anuncio',
    'medio', 'canal', 'plataforma', 'soporte', 'recurso', 'herramienta',
    'instrumento', 'utensilio', 'aparato', 'dispositivo', 'equipo', 'máquina',
    'tecnología', 'técnica', 'método', 'procedimiento', 'proceso', 'sistema',
    'mecanismo', 'funcionamiento', 'operación', 'actividad', 'acción', 'tarea',
    'trabajo', 'labor', 'faena', 'quehacer', 'ocupación', 'empleo', 'puesto',
    'profesión', 'oficio', 'carrera', 'ocupación', 'cargo', 'función', 'rol',
    'papel', 'cometido', 'misión', 'encargo', 'comisión', 'delegación',
    'jefe', 'director', 'gerente', 'administrador', 'coordinador', 'supervisor',
    'empleado', 'trabajador', 'colaborador', 'auxiliar', 'asistente', 'ayudante',
    'equipo', 'grupo', 'departamento', 'división', 'sección', 'área', 'unidad',
    'oficina', 'despacho', 'sede', 'sucursal', 'filial', 'delegación',
    'edificio', 'construcción', 'instalación', 'recinto', 'local', 'espacio',
    'sala', 'habitación', 'cuarto', 'dormitorio', 'baño', 'cocina', 'comedor',
    'ventana', 'puerta', 'pared', 'techo', 'suelo', 'piso', 'escalera',
    'mesa', 'silla', 'cama', 'armario', 'estante', 'cajón', 'alfombra',
    'luz', 'lámpara', 'bombilla', 'foco', 'iluminación', 'claridad', 'oscuridad',
    'agua', 'fuego', 'tierra', 'aire', 'viento', 'lluvia', 'nieve', 'niebla',
    'sol', 'luna', 'estrella', 'planeta', 'cielo', 'nube', 'arco iris',
    'montaña', 'valle', 'río', 'lago', 'mar', 'océano', 'playa', 'isla',
    'bosque', 'selva', 'desierto', 'pradera', 'campo', 'granja', 'jardín',
    'árbol', 'planta', 'flor', 'hoja', 'rama', 'raíz', 'tronco', 'corteza',
    'animal', 'bestia', 'criatura', 'especie', 'raza', 'variedad', 'tipo',
    'perro', 'gato', 'caballo', 'vaca', 'oveja', 'cerdo', 'gallina', 'pato',
    'pájaro', 'pez', 'insecto', 'serpiente', 'rana', 'tortuga', 'ratón',
    'comida', 'alimento', 'plato', 'receta', 'ingrediente', 'sabor', 'gusto',
    'dulce', 'salado', 'amargo', 'ácido', 'picante', 'suave', 'fuerte',
    'bebida', 'agua', 'leche', 'café', 'té', 'jugo', 'zumo', 'refresco',
    'vino', 'cerveza', 'licor', 'bebida alcohólica', 'cóctel', 'tragos',
    'desayuno', 'almuerzo', 'comida', 'cena', 'merienda', 'aperitivo', 'postre',
    'fruta', 'verdura', 'legumbre', 'cereal', 'pan', 'carne', 'pescado', 'marisco',
    'huevo', 'queso', 'leche', 'mantequilla', 'aceite', 'sal', 'azúcar', 'harina',
    'ropa', 'vestido', 'traje', 'camisa', 'pantalón', 'falda', 'chaqueta', 'abrigo',
    'zapato', 'bota', 'sandalia', 'zapatilla', 'calcetín', 'guante', 'gorro', 'sombrero',
    'joya', 'anillo', 'collar', 'pulsera', 'pendiente', 'reloj', 'gafas', 'lentes',
    'bolsa', 'maleta', 'mochila', 'cartera', 'bolso', 'paquete', 'caja', 'cajón',
    'coche', 'carro', 'automóvil', 'vehículo', 'camión', 'autobús', 'tren', 'avión',
    'barco', 'bicicleta', 'moto', 'motocicleta', 'taxi', 'metro', 'tranvía',
    'calle', 'avenida', 'carretera', 'autopista', 'camino', 'sendero', 'plaza',
    'ciudad', 'pueblo', 'villa', 'aldea', 'capital', 'metrópoli', 'urbe',
    'centro', 'barrio', 'zona', 'distrito', 'región', 'provincia', 'estado',
    'país', 'nación', 'continente', 'mundo', 'universo', 'cosmos', 'espacio',
    'tiempo', 'eternidad', 'infinito', 'nada', 'todo', 'algo', 'nada',
    'ser', 'existir', 'estar', 'haber', 'tener', 'hacer', 'poder', 'decir',
    'ver', 'dar', 'saber', 'querer', 'llegar', 'pasar', 'deber', 'poner',
    'parecer', 'quedar', 'creer', 'hablar', 'llevar', 'dejar', 'seguir',
    'venir', 'volver', 'salir', 'entrar', 'vivir', 'morir', 'nacer', 'crecer',
    'cambiar', 'empezar', 'terminar', 'acabar', 'continuar', 'parar', 'detener',
    'abrir', 'cerrar', 'subir', 'bajar', 'entrar', 'salir', 'pasar', 'cruzar',
    'correr', 'caminar', 'andar', 'marchar', 'viajar', 'volar', 'nadar', 'bucear',
    'saltar', 'caer', 'levantar', 'coger', 'tomar', 'agarrar', 'soltar', 'tirar',
    'empujar', 'arrastrar', 'mover', 'girar', 'volver', 'regresar', 'retornar',
    'buscar', 'encontrar', 'perder', 'ganar', 'conseguir', 'obtener', 'alcanzar',
    'recibir', 'dar', 'entregar', 'mandar', 'enviar', 'traer', 'llevar',
    'comprar', 'vender', 'pagar', 'cobrar', 'gastar', 'ahorrar', 'invertir',
    'costar', 'valer', 'merecer', 'importar', 'exportar', 'producir', 'fabricar',
    'crear', 'hacer', 'construir', 'edificar', 'formar', 'diseñar', 'planear',
    'organizar', 'preparar', 'ordenar', 'arreglar', 'componer', 'reparar',
    'limpiar', 'lavar', 'barrer', 'fregar', 'secar', 'planchar', 'coser',
    'cocinar', 'hornear', 'asar', 'freír', 'hervir', 'guisar', 'pelar', 'cortar',
    'comer', 'beber', 'tragar', 'masticar', 'probar', 'gustar', 'saborear',
    'dormir', 'soñar', 'despertar', 'levantar', 'acostar', 'descansar', 'relajar',
    'pensar', 'creer', 'saber', 'conocer', 'entender', 'comprender', 'aprender',
    'estudiar', 'investigar', 'analizar', 'examinar', 'observar', 'mirar', 'ver',
    'oír', 'escuchar', 'sentir', 'notar', 'percibir', 'darse cuenta', 'advertir',
    'recordar', 'acordar', 'olvidar', 'imaginar', 'suponer', 'asumir', 'presumir',
    'esperar', 'aguardar', 'desear', 'querer', 'necesitar', 'requerir', 'pedir',
    'preguntar', 'responder', 'contestar', 'hablar', 'decir', 'contar', 'explicar',
    'expresar', 'manifestar', 'declarar', 'afirmar', 'negar', 'confirmar', 'negar',
    'aceptar', 'rechazar', 'admitir', 'reconocer', 'confesar', 'revelar', 'ocultar',
    'mostrar', 'enseñar', 'demostrar', 'presentar', 'introducir', 'representar',
    'significar', 'querer decir', 'indicar', 'señalar', 'apuntar', 'marcar',
    'ayudar', 'asistir', 'apoyar', 'respaldar', 'sostener', 'mantener', 'conservar',
    'guardar', 'proteger', 'defender', 'atacar', 'luchar', 'pelear', 'combatir',
    'ganar', 'perder', 'vencer', 'derrotar', 'triunfar', 'fracasar', 'fallar',
    'lograr', 'conseguir', 'alcanzar', 'cumplir', 'realizar', 'cumplir', 'lograr',
    'intentar', 'probar', 'tratar', 'esforzar', 'merecer', 'valer la pena',
    'gustar', 'encantar', 'adorar', 'preferir', 'elegir', 'escoger', 'optar',
    'decidir', 'determinar', 'resolver', 'solucionar', 'arreglar', 'componer',
    'romper', 'quebrar', 'partir', 'dividir', 'separar', 'unir', 'juntar', 'unificar',
    'mezclar', 'combinar', 'fusionar', 'integrar', 'incluir', 'contener', 'comprender',
    'excluir', 'eliminar', 'quitar', 'sacar', 'retirar', 'borrar', 'suprimir', 'tachar',
    'añadir', 'agregar', 'sumar', 'incrementar', 'aumentar', 'crecer', 'elevar',
    'reducir', 'disminuir', 'bajar', 'minimizar', 'maximizar', 'optimizar',
    'mejorar', 'empeorar', 'avanzar', 'progresar', 'desarrollar', 'evolucionar',
    'transformar', 'convertir', 'cambiar', 'modificar', 'alterar', 'variar',
    'adaptar', 'ajustar', 'regular', 'controlar', 'manejar', 'gestionar',
    'administrar', 'dirigir', 'liderar', 'mandar', 'ordenar', 'instruir',
    'enseñar', 'educar', 'formar', 'capacitar', 'entrenar', 'preparar',
    'aprender', 'estudiar', 'practicar', 'ejercitar', 'entrenar', 'ensayar',
    'jugar', 'divertir', 'entretener', 'reír', 'llorar', 'sonreír', 'gritar',
    'cantar', 'bailar', 'tocar', 'pintar', 'dibujar', 'escribir', 'leer',
    'firmar', 'rubricar', 'sellar', 'timbrar', 'marcar', 'señalar',
    'medir', 'calcular', 'contar', 'numerar', 'cifrar', 'codificar', 'encriptar',
    'descifrar', 'decodificar', 'desencriptar', 'traducir', 'interpretar',
    'transmitir', 'comunicar', 'informar', 'notificar', 'avisar', 'alertar',
    'advertir', 'prevenir', 'proteger', 'evitar', 'impedir', 'obstaculizar',
    'permitir', 'autorizar', 'habilitar', 'activar', 'encender', 'conectar',
    'desactivar', 'apagar', 'desconectar', 'inutilizar', 'inhabilitar', 'bloquear',
    'desbloquear', 'liberar', 'soltar', 'dejar', 'permitir', 'autorizar',
    'obligar', 'forzar', 'coaccionar', 'presionar', 'amenazar', 'chantajear',
    'convencer', 'persuadir', 'seducir', 'tentar', 'atraer', 'repeler', 'ahuyentar',
    'acercar', 'alejar', 'aproximar', 'distanciar', 'unir', 'separar', 'dividir',
    'compartir', 'distribuir', 'repartir', 'asignar', 'destinar', 'reservar',
    'ocupar', 'liberar', 'desalojar', 'despejar', 'vaciar', 'llenar', 'rellenar',
    'cargar', 'descargar', 'subir', 'bajar', 'instalar', 'desinstalar',
    'configurar', 'personalizar', 'adaptar', 'ajustar', 'calibrar', 'sintonizar',
    'programar', 'codificar', 'compilar', 'ejecutar', 'correr', 'lanzar',
    'detener', 'pausar', 'suspender', 'reanudar', 'continuar', 'proseguir',
    'reiniciar', 'restablecer', 'recuperar', 'restaurar', 'volver', 'regresar',
    'actualizar', 'modernizar', 'renovar', 'reemplazar', 'sustituir', 'cambiar',
    'renovar', 'reparar', 'arreglar', 'componer', 'restaurar', 'remodelar',
    'construir', 'edificar', 'erigir', 'levantar', 'fundar', 'establecer',
    'crear', 'inventar', 'descubrir', 'hallar', 'encontrar', 'localizar',
    'identificar', 'reconocer', 'distinguir', 'diferenciar', 'comparar',
    'clasificar', 'categorizar', 'agrupar', 'organizar', 'ordenar', 'disponer',
    'colocar', 'poner', 'situar', 'ubicar', 'localizar', 'posicionar',
    'mover', 'desplazar', 'trasladar', 'transportar', 'acarrear', 'portar',
    'llevar', 'traer', 'conducir', 'guiar', 'dirigir', 'orientar', 'apuntar',
    'seguir', 'perseguir', 'cazar', 'acechar', 'rastrear', 'huella', 'seguir',
    'escapar', 'huir', 'evadir', 'eludir', 'evitar', 'esquivar', 'sortear',
    'enfrentar', 'afrontar', 'encarar', 'asumir', 'aceptar', 'admitir',
    'negar', 'rechazar', 'refutar', 'contradecir', 'oponer', 'resistir',
    'luchar', 'combatir', 'pelear', 'batallar', 'guerra', 'conflicto',
    'competir', 'rivalizar', 'concurrir', 'participar', 'intervenir',
    'colaborar', 'cooperar', 'contribuir', 'ayudar', 'asistir', 'apoyar',
    'respaldar', 'sostener', 'mantener', 'conservar', 'preservar', 'salvar',
    'proteger', 'defender', 'amparar', 'resguardar', 'custodiar', 'vigilar',
    'controlar', 'supervisar', 'monitorear', 'inspeccionar', 'revisar',
    'examinar', 'comprobar', 'verificar', 'validar', 'confirmar', 'certificar',
    'garantizar', 'asegurar'
)

$modifiedCount = 0
$translatedLines = 0
$filesModified = @()

function Contains-Spanish {
    param([string]$Line)
    # Check if line contains a comment with Spanish words
    $lowerLine = $Line.ToLower()
    foreach ($word in $spanishIndicators) {
        $lowerWord = $word.ToLower()
        if ($lowerWord.Length -gt 2 -and $lowerLine -match "\b$lowerWord\b") {
            return $true
        }
    }
    return $false
}

# Get all .pas files
$files = Get-ChildItem -Path $SourceDir -Filter '*.pas' -Recurse

$spanishFiles = @()
foreach ($file in $files) {
    $lines = Get-Content -Path $file.FullName -Encoding UTF8
    $hasSpanish = $false
    foreach ($line in $lines) {
        # Only check comment lines (lines containing //)
        if ($line -match '//' -and (Contains-Spanish $line)) {
            $hasSpanish = $true
            break
        }
    }
    if ($hasSpanish) {
        $spanishFiles += $file.FullName.Replace($SourceDir + '\', '')
    }
}

Write-Host "Files with Spanish comments found: $($spanishFiles.Count)"
$spanishFiles | ForEach-Object { Write-Host "  $_" }
