param(
    [string]$SourceDir = "D:\zPython\MakerAi\Source"
)

# Spanish to English comment translation map
# Key: Spanish pattern (regex), Value: English replacement
$translations = @(
    # Common patterns - order matters (longer/more specific first)
    @{ Pattern = '(?i)//\s*acción por defecto'; Replacement = '// default action' },
    @{ Pattern = '(?i)//\s*agregados durante'; Replacement = '// added during' },
    @{ Pattern = '(?i)//\s*al igual que'; Replacement = '// just like' },
    @{ Pattern = '(?i)//\s*al TMemo interno'; Replacement = '// to the internal TMemo' },
    @{ Pattern = '(?i)//\s*antes de sincronizar'; Replacement = '// before syncing' },
    @{ Pattern = '(?i)//\s*aunque generalmente'; Replacement = '// although generally' },
    @{ Pattern = '(?i)//\s*automáticamente'; Replacement = '// automatically' },
    @{ Pattern = '(?i)//\s*auto-inicia'; Replacement = '// auto-starts' },
    @{ Pattern = '(?i)//\s*base de datos'; Replacement = '// database' },
    @{ Pattern = '(?i)//\s*bloquear'; Replacement = '// block' },
    @{ Pattern = '(?i)//\s*cadena de texto'; Replacement = '// text string' },
    @{ Pattern = '(?i)//\s*campo'; Replacement = '// field' },
    @{ Pattern = '(?i)//\s*comprobar'; Replacement = '// check' },
    @{ Pattern = '(?i)//\s*con el'; Replacement = '// with the' },
    @{ Pattern = '(?i)//\s*con la'; Replacement = '// with the' },
    @{ Pattern = '(?i)//\s*configurar'; Replacement = '// configure' },
    @{ Pattern = '(?i)//\s*contiene'; Replacement = '// contains' },
    @{ Pattern = '(?i)//\s*crear'; Replacement = '// create' },
    @{ Pattern = '(?i)//\s*cuando'; Replacement = '// when' },
    @{ Pattern = '(?i)//\s*cuerpo del'; Replacement = '// body of the' },
    @{ Pattern = '(?i)//\s*datos'; Replacement = '// data' },
    @{ Pattern = '(?i)//\s*debe'; Replacement = '// must' },
    @{ Pattern = '(?i)//\s*debería'; Replacement = '// should' },
    @{ Pattern = '(?i)//\s*después'; Replacement = '// after' },
    @{ Pattern = '(?i)//\s*devuelve'; Replacement = '// returns' },
    @{ Pattern = '(?i)//\s*disparar'; Replacement = '// trigger' },
    @{ Pattern = '(?i)//\s*durante'; Replacement = '// during' },
    @{ Pattern = '(?i)//\s*ejecuta'; Replacement = '// executes' },
    @{ Pattern = '(?i)//\s*ejemplo'; Replacement = '// example' },
    @{ Pattern = '(?i)//\s*elemento'; Replacement = '// element' },
    @{ Pattern = '(?i)//\s*en el'; Replacement = '// in the' },
    @{ Pattern = '(?i)//\s*en la'; Replacement = '// in the' },
    @{ Pattern = '(?i)//\s*en modo'; Replacement = '// in mode' },
    @{ Pattern = '(?i)//\s*en modo async'; Replacement = '// in async mode' },
    @{ Pattern = '(?i)//\s*en OnReceiveDataEnd'; Replacement = '// in OnReceiveDataEnd' },
    @{ Pattern = '(?i)//\s*en runtime'; Replacement = '// at runtime' },
    @{ Pattern = '(?i)//\s*en el primer'; Replacement = '// in the first' },
    @{ Pattern = '(?i)//\s*en el siguiente'; Replacement = '// in the next' },
    @{ Pattern = '(?i)//\s*en el ResMsg'; Replacement = '// in the ResMsg' },
    @{ Pattern = '(?i)//\s*en el primer GetTools'; Replacement = '// in the first GetTools()' },
    @{ Pattern = '(?i)//\s*escape al TTask'; Replacement = '// escapes to TTask' },
    @{ Pattern = '(?i)//\s*escribe'; Replacement = '// writes' },
    @{ Pattern = '(?i)//\s*estado'; Replacement = '// state' },
    @{ Pattern = '(?i)//\s*esto'; Replacement = '// this' },
    @{ Pattern = '(?i)//\s*evento'; Replacement = '// event' },
    @{ Pattern = '(?i)//\s*evitando el Double Free'; Replacement = '// avoiding Double Free' },
    @{ Pattern = '(?i)//\s*evita buscar'; Replacement = '// avoids searching for' },
    @{ Pattern = '(?i)//\s*existe'; Replacement = '// exists' },
    @{ Pattern = '(?i)//\s*fichero'; Replacement = '// file' },
    @{ Pattern = '(?i)//\s*final'; Replacement = '// final/end' },
    @{ Pattern = '(?i)//\s*función'; Replacement = '// function' },
    @{ Pattern = '(?i)//\s*generar'; Replacement = '// generate' },
    @{ Pattern = '(?i)//\s*guardar'; Replacement = '// save' },
    @{ Pattern = '(?i)//\s*hacer'; Replacement = '// do/make' },
    @{ Pattern = '(?i)//\s*hasta'; Replacement = '// until' },
    @{ Pattern = '(?i)//\s*incluye'; Replacement = '// includes' },
    @{ Pattern = '(?i)//\s*indica'; Replacement = '// indicates' },
    @{ Pattern = '(?i)//\s*información'; Replacement = '// information' },
    @{ Pattern = '(?i)//\s*inicializar'; Replacement = '// initialize' },
    @{ Pattern = '(?i)//\s*inicio del'; Replacement = '// start of the' },
    @{ Pattern = '(?i)//\s*interno'; Replacement = '// internal' },
    @{ Pattern = '(?i)//\s*lanzar'; Replacement = '// launch/throw' },
    @{ Pattern = '(?i)//\s*leer'; Replacement = '// read' },
    @{ Pattern = '(?i)//\s*liberar'; Replacement = '// release/free' },
    @{ Pattern = '(?i)//\s*lista'; Replacement = '// list' },
    @{ Pattern = '(?i)//\s*llamar'; Replacement = '// call' },
    @{ Pattern = '(?i)//\s*memoria'; Replacement = '// memory' },
    @{ Pattern = '(?i)//\s*método'; Replacement = '// method' },
    @{ Pattern = '(?i)//\s*mismo'; Replacement = '// same' },
    @{ Pattern = '(?i)//\s*necesario'; Replacement = '// necessary' },
    @{ Pattern = '(?i)//\s*ninguno'; Replacement = '// none' },
    @{ Pattern = '(?i)//\s*nombre'; Replacement = '// name' },
    @{ Pattern = '(?i)//\s*nuevo'; Replacement = '// new' },
    @{ Pattern = '(?i)//\s*objeto'; Replacement = '// object' },
    @{ Pattern = '(?i)//\s*obtener'; Replacement = '// get/obtain' },
    @{ Pattern = '(?i)//\s*opcional'; Replacement = '// optional' },
    @{ Pattern = '(?i)//\s*otro'; Replacement = '// other' },
    @{ Pattern = '(?i)//\s*para'; Replacement = '// for' },
    @{ Pattern = '(?i)//\s*permite'; Replacement = '// allows' },
    @{ Pattern = '(?i)//\s*por defecto'; Replacement = '// by default' },
    @{ Pattern = '(?i)//\s*puede'; Replacement = '// can' },
    @{ Pattern = '(?i)//\s*realizar'; Replacement = '// perform' },
    @{ Pattern = '(?i)//\s*recibe'; Replacement = '// receives' },
    @{ Pattern = '(?i)//\s*referencia'; Replacement = '// reference' },
    @{ Pattern = '(?i)//\s*retorna'; Replacement = '// returns' },
    @{ Pattern = '(?i)//\s*siempre'; Replacement = '// always' },
    @{ Pattern = '(?i)//\s*sin'; Replacement = '// without' },
    @{ Pattern = '(?i)//\s*sistema'; Replacement = '// system' },
    @{ Pattern = '(?i)//\s*solo'; Replacement = '// only' },
    @{ Pattern = '(?i)//\s*también'; Replacement = '// also' },
    @{ Pattern = '(?i)//\s*tiene'; Replacement = '// has' },
    @{ Pattern = '(?i)//\s*tipo'; Replacement = '// type' },
    @{ Pattern = '(?i)//\s*todos'; Replacement = '// all' },
    @{ Pattern = '(?i)//\s*último'; Replacement = '// last' },
    @{ Pattern = '(?i)//\s*usa'; Replacement = '// uses' },
    @{ Pattern = '(?i)//\s*usando'; Replacement = '// using' },
    @{ Pattern = '(?i)//\s*utilizado'; Replacement = '// used' },
    @{ Pattern = '(?i)//\s*valor'; Replacement = '// value' },
    @{ Pattern = '(?i)//\s*variable'; Replacement = '// variable' },
    @{ Pattern = '(?i)//\s*verdadero'; Replacement = '// true' },
    @{ Pattern = '(?i)//\s*falso'; Replacement = '// false' },
    @{ Pattern = '(?i)//\s*versión'; Replacement = '// version' },
    @{ Pattern = '(?i)//\s*archivo'; Replacement = '// file' },
    @{ Pattern = '(?i)//\s*asignar'; Replacement = '// assign' },
    @{ Pattern = '(?i)//\s*actual'; Replacement = '// current' },
    @{ Pattern = '(?i)//\s*ahora'; Replacement = '// now' },
    @{ Pattern = '(?i)//\s*array'; Replacement = '// array' },
    @{ Pattern = '(?i)//\s*buffer'; Replacement = '// buffer' },
    @{ Pattern = '(?i)//\s*cargar'; Replacement = '// load' },
    @{ Pattern = '(?i)//\s*esta'; Replacement = '// this' },
    @{ Pattern = '(?i)//\s*estos'; Replacement = '// these' },
    @{ Pattern = '(?i)//\s*error'; Replacement = '// error' },
    @{ Pattern = '(?i)//\s*específico'; Replacement = '// specific' },
    @{ Pattern = '(?i)//\s*generar'; Replacement = '// generate' },
    @{ Pattern = '(?i)//\s*índice'; Replacement = '// index' },
    @{ Pattern = '(?i)//\s*auto-inicia'; Replacement = '// auto-starts' },
    @{ Pattern = '(?i)//\s*el segundo round'; Replacement = '// the second round' },
    @{ Pattern = '(?i)//\s*emitirá'; Replacement = '// will emit' },
    @{ Pattern = '(?i)//\s*No disparar'; Replacement = '// Do not trigger' },
    @{ Pattern = '(?i)//\s*si el usuario lo permite'; Replacement = '// if the user allows it' },
    @{ Pattern = '(?i)//\s*aquí lleva'; Replacement = '// here goes' },
    @{ Pattern = '(?i)//\s*conversi'; Replacement = '// conversion' },
    @{ Pattern = '(?i)//\s*los MediaFiles a texto'; Replacement = '// MediaFiles to text' },
    @{ Pattern = '(?i)//\s*ejecuta.*no cuando se crea'; Replacement = '// executes, not when created' },
    @{ Pattern = '(?i)//\s*por lo que'; Replacement = '// so' },
    @{ Pattern = '(?i)//\s*pudo haber cambiado'; Replacement = '// may have changed' },
    @{ Pattern = '(?i)//\s*original validado y probado'; Replacement = '// original validated and tested' },
    @{ Pattern = '(?i)//\s*PPM \(ppm_search'; Replacement = '// PPM (ppm_search' },
    @{ Pattern = '(?i)//\s*las crea ahora'; Replacement = '// creates them now' },
    @{ Pattern = '(?i)//\s*en runtime después de Loaded'; Replacement = '// at runtime after Loaded' },
    @{ Pattern = '(?i)//\s*en el siguiente turno'; Replacement = '// in the next turn' },
    @{ Pattern = '(?i)//\s*sin conflictos de ownership'; Replacement = '// without ownership conflicts' },
    @{ Pattern = '(?i)//\s*original.*ToolMsg.*vía driver'; Replacement = '// original -> ToolMsg (via driver)' },
    @{ Pattern = '(?i)//\s*para que el LLM los vea'; Replacement = '// so the LLM can see them' },
    @{ Pattern = '(?i)//\s*utilizar las herramientas'; Replacement = '// use the tools' },
    @{ Pattern = '(?i)//\s*api de la última'; Replacement = '// API of the last' },
    @{ Pattern = '(?i)//\s*implementación'; Replacement = '// implementation' },
    @{ Pattern = '(?i)//\s*aquí'; Replacement = '// here' },
    @{ Pattern = '(?i)//\s*índice de cada elemento'; Replacement = '// index of each element' },
    @{ Pattern = '(?i)//\s*corresponde al valor'; Replacement = '// corresponds to the value' },
    @{ Pattern = '(?i)//\s*automáticamente.*Si Start no fue llamado'; Replacement = '// automatically. If Start was not called' },
    @{ Pattern = '(?i)//\s*se auto-inicia con el'; Replacement = '// auto-starts with the' },
    @{ Pattern = '(?i)//\s*actual.*El índice'; Replacement = '// current. The index' },
    @{ Pattern = '(?i)//\s*inicio del byte'; Replacement = '// byte start' },
    @{ Pattern = '(?i)//\s*inicio del array'; Replacement = '// array start' },
    @{ Pattern = '(?i)//\s*inicio del campo'; Replacement = '// field start' },
    @{ Pattern = '(?i)//\s*evita buscar .fmx/.dfm'; Replacement = '// avoids searching for .fmx/.dfm' },
    @{ Pattern = '(?i)//\s*y cause EAggregateException'; Replacement = '// and causes EAggregateException' },
    @{ Pattern = '(?i)//\s*generalmente se quedan'; Replacement = '// generally stay' },
    @{ Pattern = '(?i)//\s*principal'; Replacement = '// main' },
    @{ Pattern = '(?i)//\s*el componente se destruya'; Replacement = '// the component is destroyed' },
    @{ Pattern = '(?i)//\s*o el componente se destruya'; Replacement = '// or the component is destroyed' },
    @{ Pattern = '(?i)//\s*termina.*o el componente'; Replacement = '// ends (or the component' },
    @{ Pattern = '(?i)//\s*o el'; Replacement = '// or the' },
    @{ Pattern = '(?i)//\s*se destruya'; Replacement = '// is destroyed' },
    @{ Pattern = '(?i)//\s*disparar evento aquí'; Replacement = '// trigger event here' },
    @{ Pattern = '(?i)//\s*el segundo round async'; Replacement = '// the second async round' },
    @{ Pattern = '(?i)//\s*proporciona'; Replacement = '// provides' },
    @{ Pattern = '(?i)//\s*consultar'; Replacement = '// query' },
    @{ Pattern = '(?i)//\s*búsqueda'; Replacement = '// search' },
    @{ Pattern = '(?i)//\s*respuesta'; Replacement = '// response' },
    @{ Pattern = '(?i)//\s*respuesta del'; Replacement = '// response from the' },
    @{ Pattern = '(?i)//\s*parámetro'; Replacement = '// parameter' },
    @{ Pattern = '(?i)//\s*punto final'; Replacement = '// endpoint' },
    @{ Pattern = '(?i)//\s*conexión'; Replacement = '// connection' },
    @{ Pattern = '(?i)//\s*configuración'; Replacement = '// configuration' },
    @{ Pattern = '(?i)//\s*imagen'; Replacement = '// image' },
    @{ Pattern = '(?i)//\s*incrustada'; Replacement = '// embedded' },
    @{ Pattern = '(?i)//\s*mensaje'; Replacement = '// message' },
    @{ Pattern = '(?i)//\s*contenido'; Replacement = '// content' },
    @{ Pattern = '(?i)//\s*probar'; Replacement = '// test' },
    @{ Pattern = '(?i)//\s*prueba'; Replacement = '// test' },
    @{ Pattern = '(?i)//\s*espera'; Replacement = '// wait' },
    @{ Pattern = '(?i)//\s*tiempo de espera'; Replacement = '// timeout' },
    @{ Pattern = '(?i)//\s*reintentar'; Replacement = '// retry' },
    @{ Pattern = '(?i)//\s*reintento'; Replacement = '// retry' },
    @{ Pattern = '(?i)//\s*agotado'; Replacement = '// exhausted' },
    @{ Pattern = '(?i)//\s*agregar'; Replacement = '// add' },
    @{ Pattern = '(?i)//\s*eliminar'; Replacement = '// remove/delete' },
    @{ Pattern = '(?i)//\s*actualizar'; Replacement = '// update' },
    @{ Pattern = '(?i)//\s*insertar'; Replacement = '// insert' },
    @{ Pattern = '(?i)//\s*consultar'; Replacement = '// query' },
    @{ Pattern = '(?i)//\s*vector'; Replacement = '// vector' },
    @{ Pattern = '(?i)//\s*vectores'; Replacement = '// vectors' },
    @{ Pattern = '(?i)//\s*grafo'; Replacement = '// graph' },
    @{ Pattern = '(?i)//\s*nodo'; Replacement = '// node' },
    @{ Pattern = '(?i)//\s*nodos'; Replacement = '// nodes' },
    @{ Pattern = '(?i)//\s*arista'; Replacement = '// edge' },
    @{ Pattern = '(?i)//\s*aristas'; Replacement = '// edges' },
    @{ Pattern = '(?i)//\s*relación'; Replacement = '// relationship' },
    @{ Pattern = '(?i)//\s*relaciones'; Replacement = '// relationships' },
    @{ Pattern = '(?i)//\s*propiedad'; Replacement = '// property' },
    @{ Pattern = '(?i)//\s*propiedades'; Replacement = '// properties' },
    @{ Pattern = '(?i)//\s*etiqueta'; Replacement = '// label' },
    @{ Pattern = '(?i)//\s*etiquetas'; Replacement = '// labels' },
    @{ Pattern = '(?i)//\s*consulta'; Replacement = '// query' },
    @{ Pattern = '(?i)//\s*resultado'; Replacement = '// result' },
    @{ Pattern = '(?i)//\s*resultados'; Replacement = '// results' },
    @{ Pattern = '(?i)//\s*proceso'; Replacement = '// process' },
    @{ Pattern = '(?i)//\s*hilo'; Replacement = '// thread' },
    @{ Pattern = '(?i)//\s*subproceso'; Replacement = '// subprocess' },
    @{ Pattern = '(?i)//\s*seguro para hilos'; Replacement = '// thread-safe' },
    @{ Pattern = '(?i)//\s*bloqueo'; Replacement = '// lock' },
    @{ Pattern = '(?i)//\s*cola'; Replacement = '// queue' },
    @{ Pattern = '(?i)//\s*pila'; Replacement = '// stack' },
    @{ Pattern = '(?i)//\s*cola de mensajes'; Replacement = '// message queue' },
    @{ Pattern = '(?i)//\s*cola de tareas'; Replacement = '// task queue' },
    @{ Pattern = '(?i)//\s*encolar'; Replacement = '// enqueue' },
    @{ Pattern = '(?i)//\s*desencolar'; Replacement = '// dequeue' },
    @{ Pattern = '(?i)//\s*vacío'; Replacement = '// empty' },
    @{ Pattern = '(?i)//\s*lleno'; Replacement = '// full' },
    @{ Pattern = '(?i)//\s*disponible'; Replacement = '// available' },
    @{ Pattern = '(?i)//\s*ocupado'; Replacement = '// busy' },
    @{ Pattern = '(?i)//\s*libre'; Replacement = '// free' },
    @{ Pattern = '(?i)//\s*activo'; Replacement = '// active' },
    @{ Pattern = '(?i)//\s*inactivo'; Replacement = '// inactive' },
    @{ Pattern = '(?i)//\s*habilitar'; Replacement = '// enable' },
    @{ Pattern = '(?i)//\s*deshabilitar'; Replacement = '// disable' },
    @{ Pattern = '(?i)//\s*activar'; Replacement = '// activate' },
    @{ Pattern = '(?i)//\s*desactivar'; Replacement = '// deactivate' },
    @{ Pattern = '(?i)//\s*iniciar'; Replacement = '// start' },
    @{ Pattern = '(?i)//\s*detener'; Replacement = '// stop' },
    @{ Pattern = '(?i)//\s*pausa'; Replacement = '// pause' },
    @{ Pattern = '(?i)//\s*reanudar'; Replacement = '// resume' },
    @{ Pattern = '(?i)//\s*continuar'; Replacement = '// continue' },
    @{ Pattern = '(?i)//\s*salir'; Replacement = '// exit' },
    @{ Pattern = '(?i)//\s*terminar'; Replacement = '// terminate' },
    @{ Pattern = '(?i)//\s*cancelar'; Replacement = '// cancel' },
    @{ Pattern = '(?i)//\s*limpiar'; Replacement = '// clear' },
    @{ Pattern = '(?i)//\s*resetear'; Replacement = '// reset' },
    @{ Pattern = '(?i)//\s*reiniciar'; Replacement = '// restart' },
    @{ Pattern = '(?i)//\s*restaurar'; Replacement = '// restore' },
    @{ Pattern = '(?i)//\s*copiar'; Replacement = '// copy' },
    @{ Pattern = '(?i)//\s*mover'; Replacement = '// move' },
    @{ Pattern = '(?i)//\s*renombrar'; Replacement = '// rename' },
    @{ Pattern = '(?i)//\s*buscar'; Replacement = '// search' },
    @{ Pattern = '(?i)//\s*encontrar'; Replacement = '// find' },
    @{ Pattern = '(?i)//\s*coincidir'; Replacement = '// match' },
    @{ Pattern = '(?i)//\s*filtrar'; Replacement = '// filter' },
    @{ Pattern = '(?i)//\s*ordenar'; Replacement = '// sort' },
    @{ Pattern = '(?i)//\s*agrupar'; Replacement = '// group' },
    @{ Pattern = '(?i)//\s*unir'; Replacement = '// join' },
    @{ Pattern = '(?i)//\s*dividir'; Replacement = '// split' },
    @{ Pattern = '(?i)//\s*combinar'; Replacement = '// combine' },
    @{ Pattern = '(?i)//\s*convertir'; Replacement = '// convert' },
    @{ Pattern = '(?i)//\s*formatear'; Replacement = '// format' },
    @{ Pattern = '(?i)//\s*parsear'; Replacement = '// parse' },
    @{ Pattern = '(?i)//\s*validar'; Replacement = '// validate' },
    @{ Pattern = '(?i)//\s*verificar'; Replacement = '// verify' },
    @{ Pattern = '(?i)//\s*comprobar'; Replacement = '// check' },
    @{ Pattern = '(?i)//\s*asegurar'; Replacement = '// ensure' },
    @{ Pattern = '(?i)//\s*garantizar'; Replacement = '// guarantee' },
    @{ Pattern = '(?i)//\s*manejar'; Replacement = '// handle' },
    @{ Pattern = '(?i)//\s*gestionar'; Replacement = '// manage' },
    @{ Pattern = '(?i)//\s*administrar'; Replacement = '// administer' },
    @{ Pattern = '(?i)//\s*controlar'; Replacement = '// control' },
    @{ Pattern = '(?i)//\s*monitorear'; Replacement = '// monitor' },
    @{ Pattern = '(?i)//\s*registrar'; Replacement = '// log/register' },
    @{ Pattern = '(?i)//\s*registro'; Replacement = '// log/registry' },
    @{ Pattern = '(?i)//\s*seguimiento'; Replacement = '// tracking' },
    @{ Pattern = '(?i)//\s*rastrear'; Replacement = '// trace' },
    @{ Pattern = '(?i)//\s*depurar'; Replacement = '// debug' },
    @{ Pattern = '(?i)//\s*perfil'; Replacement = '// profile' },
    @{ Pattern = '(?i)//\s*rendimiento'; Replacement = '// performance' },
    @{ Pattern = '(?i)//\s*optimizar'; Replacement = '// optimize' },
    @{ Pattern = '(?i)//\s*mejorar'; Replacement = '// improve' },
    @{ Pattern = '(?i)//\s*corregir'; Replacement = '// fix' },
    @{ Pattern = '(?i)//\s*reparar'; Replacement = '// repair' },
    @{ Pattern = '(?i)//\s*solucionar'; Replacement = '// solve' },
    @{ Pattern = '(?i)//\s*resolver'; Replacement = '// resolve' },
    @{ Pattern = '(?i)//\s*excepción'; Replacement = '// exception' },
    @{ Pattern = '(?i)//\s*error'; Replacement = '// error' },
    @{ Pattern = '(?i)//\s*fallo'; Replacement = '// failure' },
    @{ Pattern = '(?i)//\s*falla'; Replacement = '// fault' },
    @{ Pattern = '(?i)//\s*problema'; Replacement = '// problem' },
    @{ Pattern = '(?i)//\s*incidente'; Replacement = '// incident' },
    @{ Pattern = '(?i)//\s*advertencia'; Replacement = '// warning' },
    @{ Pattern = '(?i)//\s*informar'; Replacement = '// report' },
    @{ Pattern = '(?i)//\s*notificar'; Replacement = '// notify' },
    @{ Pattern = '(?i)//\s*aviso'; Replacement = '// notice' },
    @{ Pattern = '(?i)//\s*alerta'; Replacement = '// alert' },
    @{ Pattern = '(?i)//\s*señal'; Replacement = '// signal' },
    @{ Pattern = '(?i)//\s*bandera'; Replacement = '// flag' },
    @{ Pattern = '(?i)//\s*indicador'; Replacement = '// indicator' },
    @{ Pattern = '(?i)//\s*marcador'; Replacement = '// marker' },
    @{ Pattern = '(?i)//\s*marca'; Replacement = '// mark' },
    @{ Pattern = '(?i)//\s*señalador'; Replacement = '// pointer' },
    @{ Pattern = '(?i)//\s*puntero'; Replacement = '// pointer' },
    @{ Pattern = '(?i)//\s*referencia'; Replacement = '// reference' },
    @{ Pattern = '(?i)//\s*apuntador'; Replacement = '// pointer' },
    @{ Pattern = '(?i)//\s*dirección'; Replacement = '// address' },
    @{ Pattern = '(?i)//\s*ubicación'; Replacement = '// location' },
    @{ Pattern = '(?i)//\s*posición'; Replacement = '// position' },
    @{ Pattern = '(?i)//\s*lugar'; Replacement = '// place' },
    @{ Pattern = '(?i)//\s*espacio'; Replacement = '// space' },
    @{ Pattern = '(?i)//\s*tamaño'; Replacement = '// size' },
    @{ Pattern = '(?i)//\s*longitud'; Replacement = '// length' },
    @{ Pattern = '(?i)//\s*ancho'; Replacement = '// width' },
    @{ Pattern = '(?i)//\s*alto'; Replacement = '// height' },
    @{ Pattern = '(?i)//\s*profundidad'; Replacement = '// depth' },
    @{ Pattern = '(?i)//\s*dimensión'; Replacement = '// dimension' },
    @{ Pattern = '(?i)//\s*dimensiones'; Replacement = '// dimensions' },
    @{ Pattern = '(?i)//\s*forma'; Replacement = '// shape' },
    @{ Pattern = '(?i)//\s*estructura'; Replacement = '// structure' },
    @{ Pattern = '(?i)//\s*organización'; Replacement = '// organization' },
    @{ Pattern = '(?i)//\s*disposición'; Replacement = '// layout' },
    @{ Pattern = '(?i)//\s*arreglo'; Replacement = '// arrangement' },
    @{ Pattern = '(?i)//\s*colección'; Replacement = '// collection' },
    @{ Pattern = '(?i)//\s*conjunto'; Replacement = '// set' },
    @{ Pattern = '(?i)//\s*grupo'; Replacement = '// group' },
    @{ Pattern = '(?i)//\s*paquete'; Replacement = '// package' },
    @{ Pattern = '(?i)//\s*módulo'; Replacement = '// module' },
    @{ Pattern = '(?i)//\s*componente'; Replacement = '// component' },
    @{ Pattern = '(?i)//\s*módulos'; Replacement = '// modules' },
    @{ Pattern = '(?i)//\s*partes'; Replacement = '// parts' },
    @{ Pattern = '(?i)//\s*piezas'; Replacement = '// pieces' },
    @{ Pattern = '(?i)//\s*elementos'; Replacement = '// elements' },
    @{ Pattern = '(?i)//\s*ítems'; Replacement = '// items' },
    @{ Pattern = '(?i)//\s*entradas'; Replacement = '// entries' },
    @{ Pattern = '(?i)//\s*registros'; Replacement = '// records' },
    @{ Pattern = '(?i)//\s*filas'; Replacement = '// rows' },
    @{ Pattern = '(?i)//\s*columnas'; Replacement = '// columns' },
    @{ Pattern = '(?i)//\s*campos'; Replacement = '// fields' },
    @{ Pattern = '(?i)//\s*atributos'; Replacement = '// attributes' },
    @{ Pattern = '(?i)//\s*características'; Replacement = '// characteristics' },
    @{ Pattern = '(?i)//\s*detalles'; Replacement = '// details' },
    @{ Pattern = '(?i)//\s*especificaciones'; Replacement = '// specifications' },
    @{ Pattern = '(?i)//\s*parámetros'; Replacement = '// parameters' },
    @{ Pattern = '(?i)//\s*argumentos'; Replacement = '// arguments' },
    @{ Pattern = '(?i)//\s*valores'; Replacement = '// values' },
    @{ Pattern = '(?i)//\s*datos de entrada'; Replacement = '// input data' },
    @{ Pattern = '(?i)//\s*datos de salida'; Replacement = '// output data' },
    @{ Pattern = '(?i)//\s*entrada'; Replacement = '// input' },
    @{ Pattern = '(?i)//\s*salida'; Replacement = '// output' },
    @{ Pattern = '(?i)//\s*flujo'; Replacement = '// flow/stream' },
    @{ Pattern = '(?i)//\s*corriente'; Replacement = '// stream' },
    @{ Pattern = '(?i)//\s*transmisión'; Replacement = '// transmission' },
    @{ Pattern = '(?i)//\s*recepción'; Replacement = '// reception' },
    @{ Pattern = '(?i)//\s*envío'; Replacement = '// sending' },
    @{ Pattern = '(?i)//\s*recibir'; Replacement = '// receive' },
    @{ Pattern = '(?i)//\s*enviar'; Replacement = '// send' },
    @{ Pattern = '(?i)//\s*transmitir'; Replacement = '// transmit' },
    @{ Pattern = '(?i)//\s*propagar'; Replacement = '// propagate' },
    @{ Pattern = '(?i)//\s*difundir'; Replacement = '// broadcast' },
    @{ Pattern = '(?i)//\s*publicar'; Replacement = '// publish' },
    @{ Pattern = '(?i)//\s*suscribir'; Replacement = '// subscribe' },
    @{ Pattern = '(?i)//\s*suscripción'; Replacement = '// subscription' },
    @{ Pattern = '(?i)//\s*canal'; Replacement = '// channel' },
    @{ Pattern = '(?i)//\s*canales'; Replacement = '// channels' },
    @{ Pattern = '(?i)//\s*puerto'; Replacement = '// port' },
    @{ Pattern = '(?i)//\s*host'; Replacement = '// host' },
    @{ Pattern = '(?i)//\s*servidor'; Replacement = '// server' },
    @{ Pattern = '(?i)//\s*cliente'; Replacement = '// client' },
    @{ Pattern = '(?i)//\s*red'; Replacement = '// network' },
    @{ Pattern = '(?i)//\s*protocolo'; Replacement = '// protocol' },
    @{ Pattern = '(?i)//\s*interfaz'; Replacement = '// interface' },
    @{ Pattern = '(?i)//\s*adaptador'; Replacement = '// adapter' },
    @{ Pattern = '(?i)//\s*puente'; Replacement = '// bridge' },
    @{ Pattern = '(?i)//\s*conector'; Replacement = '// connector' },
    @{ Pattern = '(?i)//\s*envoltorio'; Replacement = '// wrapper' },
    @{ Pattern = '(?i)//\s*envoltura'; Replacement = '// wrapper' },
    @{ Pattern = '(?i)//\s*adaptador'; Replacement = '// adapter' },
    @{ Pattern = '(?i)//\s*fachada'; Replacement = '// facade' },
    @{ Pattern = '(?i)//\s*patrón'; Replacement = '// pattern' },
    @{ Pattern = '(?i)//\s*diseño'; Replacement = '// design' },
    @{ Pattern = '(?i)//\s*arquitectura'; Replacement = '// architecture' },
    @{ Pattern = '(?i)//\s*implementación'; Replacement = '// implementation' },
    @{ Pattern = '(?i)//\s*abstracción'; Replacement = '// abstraction' },
    @{ Pattern = '(?i)//\s*encapsulamiento'; Replacement = '// encapsulation' },
    @{ Pattern = '(?i)//\s*herencia'; Replacement = '// inheritance' },
    @{ Pattern = '(?i)//\s*polimorfismo'; Replacement = '// polymorphism' },
    @{ Pattern = '(?i)//\s*interfaz'; Replacement = '// interface' },
    @{ Pattern = '(?i)//\s*clase'; Replacement = '// class' },
    @{ Pattern = '(?i)//\s*objeto'; Replacement = '// object' },
    @{ Pattern = '(?i)//\s*instancia'; Replacement = '// instance' },
    @{ Pattern = '(?i)//\s*método'; Replacement = '// method' },
    @{ Pattern = '(?i)//\s*función'; Replacement = '// function' },
    @{ Pattern = '(?i)//\s*procedimiento'; Replacement = '// procedure' },
    @{ Pattern = '(?i)//\s*rutina'; Replacement = '// routine' },
    @{ Pattern = '(?i)//\s*subrutina'; Replacement = '// subroutine' },
    @{ Pattern = '(?i)//\s*llamada'; Replacement = '// call' },
    @{ Pattern = '(?i)//\s*invocación'; Replacement = '// invocation' },
    @{ Pattern = '(?i)//\s*ejecución'; Replacement = '// execution' },
    @{ Pattern = '(?i)//\s*ejecutar'; Replacement = '// execute' },
    @{ Pattern = '(?i)//\s*correr'; Replacement = '// run' },
    @{ Pattern = '(?i)//\s*ejecuta.*no cuando'; Replacement = '// executes, not when' },
    @{ Pattern = '(?i)//\s*creado'; Replacement = '// created' },
    @{ Pattern = '(?i)//\s*destruido'; Replacement = '// destroyed' },
    @{ Pattern = '(?i)//\s*destruir'; Replacement = '// destroy' },
    @{ Pattern = '(?i)//\s*constructor'; Replacement = '// constructor' },
    @{ Pattern = '(?i)//\s*destructor'; Replacement = '// destructor' },
    @{ Pattern = '(?i)//\s*inicialización'; Replacement = '// initialization' },
    @{ Pattern = '(?i)//\s*finalización'; Replacement = '// finalization' },
    @{ Pattern = '(?i)//\s*limpieza'; Replacement = '// cleanup' },
    @{ Pattern = '(?i)//\s*recursos'; Replacement = '// resources' },
    @{ Pattern = '(?i)//\s*recurso'; Replacement = '// resource' },
    @{ Pattern = '(?i)//\s*asignación'; Replacement = '// allocation' },
    @{ Pattern = '(?i)//\s*reserva'; Replacement = '// reservation' },
    @{ Pattern = '(?i)//\s*liberación'; Replacement = '// release' },
    @{ Pattern = '(?i)//\s*disponibilidad'; Replacement = '// availability' },
    @{ Pattern = '(?i)//\s*acceso'; Replacement = '// access' },
    @{ Pattern = '(?i)//\s*acceder'; Replacement = '// access' },
    @{ Pattern = '(?i)//\s*lectura'; Replacement = '// reading' },
    @{ Pattern = '(?i)//\s*escritura'; Replacement = '// writing' },
    @{ Pattern = '(?i)//\s*modificación'; Replacement = '// modification' },
    @{ Pattern = '(?i)//\s*modificar'; Replacement = '// modify' },
    @{ Pattern = '(?i)//\s*cambio'; Replacement = '// change' },
    @{ Pattern = '(?i)//\s*cambiar'; Replacement = '// change' },
    @{ Pattern = '(?i)//\s*transformación'; Replacement = '// transformation' },
    @{ Pattern = '(?i)//\s*transformar'; Replacement = '// transform' },
    @{ Pattern = '(?i)//\s*mapeo'; Replacement = '// mapping' },
    @{ Pattern = '(?i)//\s*mapear'; Replacement = '// map' },
    @{ Pattern = '(?i)//\s*asignación'; Replacement = '// assignment' },
    @{ Pattern = '(?i)//\s*mapeado'; Replacement = '// mapped' },
    @{ Pattern = '(?i)//\s*correspondencia'; Replacement = '// correspondence' },
    @{ Pattern = '(?i)//\s*equivalencia'; Replacement = '// equivalence' },
    @{ Pattern = '(?i)//\s*igualdad'; Replacement = '// equality' },
    @{ Pattern = '(?i)//\s*comparación'; Replacement = '// comparison' },
    @{ Pattern = '(?i)//\s*comparar'; Replacement = '// compare' },
    @{ Pattern = '(?i)//\s*igual'; Replacement = '// equal' },
    @{ Pattern = '(?i)//\s*diferente'; Replacement = '// different' },
    @{ Pattern = '(?i)//\s*distinto'; Replacement = '// distinct' },
    @{ Pattern = '(?i)//\s*similar'; Replacement = '// similar' },
    @{ Pattern = '(?i)//\s*semejante'; Replacement = '// alike' },
    @{ Pattern = '(?i)//\s*aproximado'; Replacement = '// approximate' },
    @{ Pattern = '(?i)//\s*exacto'; Replacement = '// exact' },
    @{ Pattern = '(?i)//\s*preciso'; Replacement = '// precise' },
    @{ Pattern = '(?i)//\s*correcto'; Replacement = '// correct' },
    @{ Pattern = '(?i)//\s*incorrecto'; Replacement = '// incorrect' },
    @{ Pattern = '(?i)//\s*inválido'; Replacement = '// invalid' },
    @{ Pattern = '(?i)//\s*válido'; Replacement = '// valid' },
    @{ Pattern = '(?i)//\s*válido y probado'; Replacement = '// valid and tested' },
    @{ Pattern = '(?i)//\s*inválido'; Replacement = '// invalid' },
    @{ Pattern = '(?i)//\s*seguro'; Replacement = '// safe' },
    @{ Pattern = '(?i)//\s*inseguro'; Replacement = '// unsafe' },
    @{ Pattern = '(?i)//\s*protegido'; Replacement = '// protected' },
    @{ Pattern = '(?i)//\s*privado'; Replacement = '// private' },
    @{ Pattern = '(?i)//\s*público'; Replacement = '// public' },
    @{ Pattern = '(?i)//\s*oculto'; Replacement = '// hidden' },
    @{ Pattern = '(?i)//\s*visible'; Replacement = '// visible' },
    @{ Pattern = '(?i)//\s*invisible'; Replacement = '// invisible' },
    @{ Pattern = '(?i)//\s*explícito'; Replacement = '// explicit' },
    @{ Pattern = '(?i)//\s*implícito'; Replacement = '// implicit' },
    @{ Pattern = '(?i)//\s*directo'; Replacement = '// direct' },
    @{ Pattern = '(?i)//\s*indirecto'; Replacement = '// indirect' },
    @{ Pattern = '(?i)//\s*inmediato'; Replacement = '// immediate' },
    @{ Pattern = '(?i)//\s*diferido'; Replacement = '// deferred' },
    @{ Pattern = '(?i)//\s*retrasado'; Replacement = '// delayed' },
    @{ Pattern = '(?i)//\s*atrasado'; Replacement = '// behind/delayed' },
    @{ Pattern = '(?i)//\s*pendiente'; Replacement = '// pending' },
    @{ Pattern = '(?i)//\s*esperando'; Replacement = '// waiting' },
    @{ Pattern = '(?i)//\s*en espera'; Replacement = '// on hold' },
    @{ Pattern = '(?i)//\s*en curso'; Replacement = '// in progress' },
    @{ Pattern = '(?i)//\s*en progreso'; Replacement = '// in progress' },
    @{ Pattern = '(?i)//\s*completado'; Replacement = '// completed' },
    @{ Pattern = '(?i)//\s*terminado'; Replacement = '// finished' },
    @{ Pattern = '(?i)//\s*finalizado'; Replacement = '// finalized' },
    @{ Pattern = '(?i)//\s*exitoso'; Replacement = '// successful' },
    @{ Pattern = '(?i)//\s*éxito'; Replacement = '// success' },
    @{ Pattern = '(?i)//\s*fallido'; Replacement = '// failed' },
    @{ Pattern = '(?i)//\s*fracaso'; Replacement = '// failure' },
    @{ Pattern = '(?i)//\s*rechazado'; Replacement = '// rejected' },
    @{ Pattern = '(?i)//\s*aceptado'; Replacement = '// accepted' },
    @{ Pattern = '(?i)//\s*confirmado'; Replacement = '// confirmed' },
    @{ Pattern = '(?i)//\s*pendiente de confirmación'; Replacement = '// pending confirmation' },
    @{ Pattern = '(?i)//\s*por confirmar'; Replacement = '// to be confirmed' },
    @{ Pattern = '(?i)//\s*por defecto.*bloquear'; Replacement = '// default: block' },
    @{ Pattern = '(?i)//\s*por defecto: bloquear'; Replacement = '// default: block' },
    @{ Pattern = '(?i)//\s*acción por defecto.*bloquear'; Replacement = '// default action: block' },
    @{ Pattern = '(?i)//\s*por defecto'; Replacement = '// default' },
    @{ Pattern = '(?i)//\s*predeterminado'; Replacement = '// default' },
    @{ Pattern = '(?i)//\s*por omisión'; Replacement = '// by default' },
    @{ Pattern = '(?i)//\s*automático'; Replacement = '// automatic' },
    @{ Pattern = '(?i)//\s*manual'; Replacement = '// manual' },
    @{ Pattern = '(?i)//\s*opcional'; Replacement = '// optional' },
    @{ Pattern = '(?i)//\s*requerido'; Replacement = '// required' },
    @{ Pattern = '(?i)//\s*obligatorio'; Replacement = '// mandatory' },
    @{ Pattern = '(?i)//\s*necesario'; Replacement = '// necessary' },
    @{ Pattern = '(?i)//\s*innecesario'; Replacement = '// unnecessary' },
    @{ Pattern = '(?i)//\s*importante'; Replacement = '// important' },
    @{ Pattern = '(?i)//\s*crítico'; Replacement = '// critical' },
    @{ Pattern = '(?i)//\s*crítica'; Replacement = '// critical' },
    @{ Pattern = '(?i)//\s*secundario'; Replacement = '// secondary' },
    @{ Pattern = '(?i)//\s*primario'; Replacement = '// primary' },
    @{ Pattern = '(?i)//\s*principal'; Replacement = '// main' },
    @{ Pattern = '(?i)//\s*secundario'; Replacement = '// secondary' },
    @{ Pattern = '(?i)//\s*alternativo'; Replacement = '// alternative' },
    @{ Pattern = '(?i)//\s*oppcional'; Replacement = '// optional' },
    @{ Pattern = '(?i)//\s*adicional'; Replacement = '// additional' },
    @{ Pattern = '(?i)//\s*extra'; Replacement = '// extra' },
    @{ Pattern = '(?i)//\s*suplementario'; Replacement = '// supplementary' },
    @{ Pattern = '(?i)//\s*complementario'; Replacement = '// complementary' },
    @{ Pattern = '(?i)//\s*adicional'; Replacement = '// additional' },
    @{ Pattern = '(?i)//\s*extra'; Replacement = '// extra' },
    @{ Pattern = '(?i)//\s*adicional'; Replacement = '// additional' },
    @{ Pattern = '(?i)//\s*remover'; Replacement = '// remove' },
    @{ Pattern = '(?i)//\s*quitar'; Replacement = '// remove' },
    @{ Pattern = '(?i)//\s*sacar'; Replacement = '// take out' },
    @{ Pattern = '(?i)//\s*extraer'; Replacement = '// extract' },
    @{ Pattern = '(?i)//\s*extraido'; Replacement = '// extracted' },
    @{ Pattern = '(?i)//\s*extraído'; Replacement = '// extracted' },
    @{ Pattern = '(?i)//\s*extraer'; Replacement = '// extract' },
    @{ Pattern = '(?i)//\s*obtenido'; Replacement = '// obtained' },
    @{ Pattern = '(?i)//\s*obtener'; Replacement = '// obtain' },
    @{ Pattern = '(?i)//\s*conseguir'; Replacement = '// get' },
    @{ Pattern = '(?i)//\s*alcanzar'; Replacement = '// reach' },
    @{ Pattern = '(?i)//\s*lograr'; Replacement = '// achieve' },
    @{ Pattern = '(?i)//\s*conseguir'; Replacement = '// get/achieve' },
    @{ Pattern = '(?i)//\s*devolver'; Replacement = '// return' },
    @{ Pattern = '(?i)//\s*retorno'; Replacement = '// return' },
    @{ Pattern = '(?i)//\s*retorno de llamada'; Replacement = '// callback' },
    @{ Pattern = '(?i)//\s*llamada de retorno'; Replacement = '// callback' },
    @{ Pattern = '(?i)//\s*retorno de función'; Replacement = '// function return' },
    @{ Pattern = '(?i)//\s*valor de retorno'; Replacement = '// return value' },
    @{ Pattern = '(?i)//\s*valor devuelto'; Replacement = '// returned value' },
    @{ Pattern = '(?i)//\s*resultado'; Replacement = '// result' },
    @{ Pattern = '(?i)//\s*salida'; Replacement = '// output' },
    @{ Pattern = '(?i)//\s*producto'; Replacement = '// product' },
    @{ Pattern = '(?i)//\s*efecto'; Replacement = '// effect' },
    @{ Pattern = '(?i)//\s*impacto'; Replacement = '// impact' },
    @{ Pattern = '(?i)//\s*consecuencia'; Replacement = '// consequence' },
    @{ Pattern = '(?i)//\s*resultado final'; Replacement = '// final result' },
    @{ Pattern = '(?i)//\s*conclusión'; Replacement = '// conclusion' },
    @{ Pattern = '(?i)//\s*cierre'; Replacement = '// closing' },
    @{ Pattern = '(?i)//\s*final'; Replacement = '// end' },
    @{ Pattern = '(?i)//\s*fin'; Replacement = '// end' },
    @{ Pattern = '(?i)//\s*terminación'; Replacement = '// termination' },
    @{ Pattern = '(?i)//\s*comienzo'; Replacement = '// beginning' },
    @{ Pattern = '(?i)//\s*inicio'; Replacement = '// start' },
    @{ Pattern = '(?i)//\s*principio'; Replacement = '// beginning' },
    @{ Pattern = '(?i)//\s*origen'; Replacement = '// origin' },
    @{ Pattern = '(?i)//\s*fuente'; Replacement = '// source' },
    @{ Pattern = '(?i)//\s*destino'; Replacement = '// destination' },
    @{ Pattern = '(?i)//\s*meta'; Replacement = '// goal' },
    @{ Pattern = '(?i)//\s*objetivo'; Replacement = '// objective' },
    @{ Pattern = '(?i)//\s*propósito'; Replacement = '// purpose' },
    @{ Pattern = '(?i)//\s*intención'; Replacement = '// intention' },
    @{ Pattern = '(?i)//\s*razón'; Replacement = '// reason' },
    @{ Pattern = '(?i)//\s*motivo'; Replacement = '// motive' },
    @{ Pattern = '(?i)//\s*causa'; Replacement = '// cause' },
    @{ Pattern = '(?i)//\s*efecto'; Replacement = '// effect' },
    @{ Pattern = '(?i)//\s*consecuencia'; Replacement = '// consequence' },
    @{ Pattern = '(?i)//\s*resultado'; Replacement = '// result' },
    @{ Pattern = '(?i)//\s*consecuencia'; Replacement = '// consequence' },
    # Block comment patterns
    @{ Pattern = '(?i)\{\s*.*acción.*\}'; Replacement = '// action' },
    @{ Pattern = '(?i)\(\*\s*.*acción.*\*\)'; Replacement = '// action' },
)

$modifiedCount = 0
$translatedLines = 0
$filesModified = @()

# Get all .pas files
$files = Get-ChildItem -Path $SourceDir -Filter '*.pas' -Recurse

foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    $originalContent = $content
    $fileModified = $false

    foreach ($t in $translations) {
        $matches = [regex]::Matches($content, $t.Pattern)
        if ($matches.Count -gt 0) {
            $content = [regex]::Replace($content, $t.Pattern, $t.Replacement)
            $fileModified = $true
            $translatedLines += $matches.Count
        }
    }

    if ($fileModified) {
        # Write back with UTF8 BOM
        [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.UTF8Encoding]::new($true))
        $modifiedCount++
        $filesModified += $file.FullName.Replace($SourceDir + '\', '')
    }
}

Write-Host "=== Translation Summary ==="
Write-Host "Files modified: $modifiedCount"
Write-Host "Comment lines translated: $translatedLines"
Write-Host ""
Write-Host "Files changed:"
$filesModified | ForEach-Object { Write-Host "  $_" }
