import os
import re

source_dir = r"D:\zPython\MakerAi\Source"

# Comprehensive Spanish -> English translation map for code comments
# Keys are Spanish regex patterns, values are English replacements
# Order matters: longer/more specific patterns first
translations = [
    # Full-line patterns (most specific first)
    (r'// Interfaz unificada de herramientas para el rediseño del sistema de agentes\.',
     '// Unified tool interface for the agent system redesign.'),
    (r'// Autor: Gustavo Enrнquez',
     '// Author: Gustavo Enriquez'),
    (r'// Nombre: Gustavo Enrнquez',
     '// Name: Gustavo Enriquez'),
    (r'// Actualizaci\xf3n: Integraci\xf3n API Gemini 3 \(Thinking Level, Signatures, Media Resolution\)',
     '// Update: Gemini 3 API Integration (Thinking Level, Signatures, Media Resolution)'),
    (r'// Uso b\xe1sico:',
     '// Basic usage:'),
    (r'// Centralizado aqu\xed para que cualquier app que use uMakerAi\.Chat\.Initializations',
     '// Centralized here so any app using uMakerAi.Chat.Initializations'),
    (r'// tenga todos los drivers disponibles autom\xe1ticamente\.',
     '// has all drivers available automatically.'),
    (r'// Implementaci\xf3n base vac\xeda\.',
     '// Empty base implementation.'),
    (r'// sobreescriben este m\xe9todo para procesar los bloques \{"type":"text"/"thinking",\.\.\.\}\.',
     '// override this method to process {"type":"text"/"thinking",...} blocks.'),
    (r'// Acci\xf3n por defecto: bloquear',
     '// Default action: block'),
    (r'// acci\xf3n por defecto: bloquear',
     '// default action: block'),
    (r'// evita buscar \.fmx/\.dfm',
     '// avoids searching for .fmx/.dfm'),
    (r'// aqu\xed lleva el Prompt Inicial \+ la conversi\xf3n de los MediaFiles a texto si el usuario lo permite',
     '// here goes the Initial Prompt + conversion of MediaFiles to text if user allows'),
    (r'// Las funciones no trabajan en modo asc\xedncrono',
     '// Functions do not work in async mode'),
    (r'// Siempre liberar el estado de ocupado en errores HTTP \(ej: 429 rate limit,',
     '// Always release busy state on HTTP errors (e.g. 429 rate limit,'),
    (r'// 500 server error, etc\)\. Sin esto la app queda colgada indefinidamente\.',
     '// 500 server error, etc). Without this the app hangs indefinitely.'),
    (r'// Subrutina local: garantiza captura independiente por valor en Delphi 10\.4\+',
     '// Local subroutine: guarantees independent capture by value in Delphi 10.4+'),
    (r'// \(la asignaci\xf3n LCaptura:=ToolCall dentro del anon-proc corre cuando el task',
     '// (the assignment LCaptura:=ToolCall inside the anon-proc runs when the task'),
    (r'// ejecuta, no cuando se crea, por lo que ToolCall pudo haber cambiado\)',
     '// executes, not when created, so ToolCall may have changed)'),
    (r'// Clase base no hace nada',
     '// Base class does nothing'),
    (r'// CORREGIDO: Solo liberamos si Run cre\xf3 el objeto\.',
     '// FIXED: Only free if Run created the object.'),
    (r'// Si viene de ParseChat \(Tool Call\), LOwnsResMsg es False, no se libera aqu\xed,',
     '// If from ParseChat (Tool Call), LOwnsResMsg is False, not freed here,'),
    (r'// evitando el Double Free en OnInternalReceiveData\.',
     '// avoiding Double Free in OnInternalReceiveData.'),
    (r'// original validado y probado',
     '// original validated and tested'),
    (r'// OJO Activar',
     '// NOTE: Activate'),
    (r'// Guarda las transcripciones en los MediaFile,  luego construye la respuesta definitiva con todos los mediafiles',
     '// Saves transcriptions in MediaFile, then builds the definitive response with all mediafiles'),
    (r'// al TMemo interno\.',
     '// to the internal TMemo.'),
    (r'// agregados durante tool calls\)\. Si no, crear uno nuevo\.',
     '// added during tool calls). If not, create a new one.'),
    (r'// al igual que \'googleSearch\' o \'codeExecution\'\.',
     '// just like \'googleSearch\' or \'codeExecution\'.'),
    (r'// el TTask termine \(o el componente se destruya\)\.',
     '// the TTask ends (or the component is destroyed).'),
    (r'// en OnReceiveDataEnd sin conflictos de ownership\.',
     '// in OnReceiveDataEnd without ownership conflicts.'),
    (r'// en runtime despu\xe9s de Loaded\), las crea ahora\.',
     '// at runtime after Loaded), creates them now.'),
    (r'// en el primer GetTools\(\) o DoCallFunction\(\) cuando Active=True\.',
     '// in the first GetTools() or DoCallFunction() when Active=True.'),
    (r'// antes de sincronizar el resto de propiedades\.',
     '// before syncing the rest of properties.'),
    (r'// al LLM a utilizar las herramientas PPM \(ppm_search, ppm_install, call_mcp_tool\)\.',
     '// to the LLM to use PPM tools (ppm_search, ppm_install, call_mcp_tool).'),
    (r'// en OnReceiveDataEnd sin conflictos de ownership\.',
     '// in OnReceiveDataEnd without ownership conflicts.'),
    (r'// Archivos extra\xeddos por el tool \(ej: im\xe1genes devueltas por MCP\)',
     '// Files extracted by the tool (e.g. images returned by MCP)'),
    (r'// Archivos extra\xeddos тЖТ ToolCall\.MediaFiles \(los drivers los transfieren',
     '// Extracted files тЖТ ToolCall.MediaFiles (drivers transfer them'),
    (r'// al ToolMsg para que el LLM los vea en el siguiente turno\)\.',
     '// to ToolMsg so the LLM can see them in the next turn).'),
    (r'// original тЖТ ToolMsg \(v\xeda driver\)',
     '// original тЖТ ToolMsg (via driver)'),
    (r'// Setear Response para que el driver pueda enviar un tool result v\xe1lido al LLM\.',
     '// Set Response so the driver can send a valid tool result to the LLM.'),
    (r'// Reemplazar separador MCP por --> para visualizaci\xf3n',
     '// Replace MCP separator with --> for display'),
    (r'// Escape characters in JSON strings',
     '// Escape characters in JSON strings'),
    (r'// Handles %XX and multi-byte UTF-8 sequences \(%C3%A9 тЖТ \xc3\xa9, %EF%BD%89 тЖТ я╜Й\)\.',
     '// Handles %XX and multi-byte UTF-8 sequences (%C3%A9 тЖТ ├й, %EF%BD%89 тЖТ я╜Й).'),
    (r'/// Handles multi-byte UTF-8 sequences \(%C3%A9 тЖТ \xc3\xa9, %EF%BD%89 тЖТ я╜Й\)\.',
     '/// Handles multi-byte UTF-8 sequences (%C3%A9 тЖТ ├й, %EF%BD%89 тЖТ я╜Й).'),
    (r'// Handles multi-byte UTF-8 sequences \(%C3%A9 тЖТ \xc3\xa9, %EF%BD%89 тЖТ я╜Й\)\.',
     '// Handles multi-byte UTF-8 sequences (%C3%A9 тЖТ ├й, %EF%BD%89 тЖТ я╜Й).'),
    (r'// escape al TTask system y cause EAggregateException en WaitForAll\.',
     '// escapes to TTask system and causes EAggregateException in WaitForAll.'),
    (r'// aunque generalmente se quedan en el ResMsg principal',
     '// although they generally stay in the main ResMsg'),
    (r'// Endpoint: https://api\.anthropic\.com/v1/files/\{file_id\}/content',
     '// Endpoint: https://api.anthropic.com/v1/files/{file_id}/content'),
    (r'// api de la \xfaltima implementaci\xf3n \{/beta/\}',
     '// API of the last implementation {/beta/}'),
    (r'// el segundo round en modo async \(stream=true\)\. El segundo round',
     '// the second round in async mode (stream=true). The second round'),
    (r'// emitir\xe1 sus propios eventos \(SSE тЖТ \[DONE\] тЖТ FOnReceiveDataEnd\)\.',
     '// will emit its own events (SSE тЖТ [DONE] тЖТ FOnReceiveDataEnd).'),
    (r'// el segundo round async\. No disparar evento aqu\xed\.',
     '// the second async round. Do not trigger event here.'),
    (r'// razonamiento contenido requerido por APIs como DeepSeek y Kimi cuando thinking est\xe1 habilitado\.',
     '// reasoning_content required by APIs like DeepSeek and Kimi when thinking is enabled.'),
    (r'// Solo se serializa cuando est\xe1 presente \(no afecta a providers que no lo usan\)\.',
     '// Only serialized when present (does not affect providers that do not use it).'),
    (r'// evento para que el desarrollador apruebe o deniegue la instalaci\xf3n de un paquete MCP v\xeda AutoMCP\.',
     '// event for the developer to approve or deny installation of an MCP package via AutoMCP.'),
    (r'\(Gemini, OpenAI, Claude, Ollama\) requieren base64 sin saltos de l\xednea\.',
     '(Gemini, OpenAI, Claude, Ollama) require base64 without line breaks.'),
    (r'// Integraci\xf3n con PPM \(registry p\xfablico de prompts\)',
     '// Integration with PPM (public prompts registry)'),
    (r'// AVersion vac\xedo = resuelve la \xfaltima versi\xf3n disponible\.',
     '// Empty AVersion = resolves the latest available version.'),
    (r'// Error de red: retorna vac\xedo',
     '// Network error: returns empty'),
    (r'// Error de red: devolver lista vac\xeda',
     '// Network error: return empty list'),
    (r'// Si no hay versi\xf3n, primero obtenemos la \xfaltima versi\xf3n no-yanked del listado,',
     '// If no version, first get the latest non-yanked version from the listing,'),
    (r'// Si no viene versi\xf3n, resolver la \xfaltima desde GET /v1/packages/\{name\}',
     '// If no version comes, resolve the latest from GET /v1/packages/{name}'),
    (r'// Tomar la primera versi\xf3n no-yanked \(el registry las devuelve en orden descendente\)',
     '// Take the first non-yanked version (the registry returns them in descending order)'),
    (r'// Descarga, extrae y devuelve el path del ejecutable seg\xfan \[mcp\] entrypoint=\.\.\.',
     '// Downloads, extracts and returns the executable path according to [mcp] entrypoint=...'),
    (r'// Directorio de extracci\xf3n: tools\\mcp-nombre\\',
     '// Extraction directory: tools\\mcp-name\\'),
    (r'// Si ya est\xe1 extra\xeddo, leer entrypoint del manifiesto y devolver',
     '// If already extracted, read entrypoint from manifest and return'),
    (r'// funci\xf3n LLM, servidor MCP, o herramienta PPM descargada\)\.',
     '// LLM function, MCP server, or downloaded PPM tool).'),
    (r'// extracci\xf3n fallida',
     '// extraction failed'),
    (r'// Leer entrypoint del manifiesto extra\xeddo',
     '// Read entrypoint from extracted manifest'),
    (r'// Si no tenemos DownloadUrl, obtener info completa del paquete v\xeda registry',
     '// If no DownloadUrl, get full package info via registry'),
    (r'// Devuelve el n\xfamero de herramientas registradas \(0 = fallo\)\.',
     '// Returns the number of registered tools (0 = failure).'),
    (r'// Devuelve el n\xfamero total de herramientas registradas\.',
     '// Returns the total number of registered tools.'),
    (r'// Si est\xe1 vac\xedo usa %APPDATA%\\MakerAI\\tools\\',
     '// If empty uses %APPDATA%\\MakerAI\\tools\\'),
    (r'// ref d\xe9bil тАФ no owning',
     '// weak ref тАФ not owning'),
    (r'// Registro unificado de herramientas IAiTool con integraci\xf3n PPM\.',
     '// Unified registry of IAiTool tools with PPM integration.'),
    (r'// Inicializar si todav\xeda no se hizo',
     '// Initialize if not yet done'),
    (r'// A\xf1adir al registry:',
     '// Add to registry:'),
    (r'// Notificar al padre para recalcular tama\xf1o\.',
     '// Notify parent to recalculate size.'),
    (r'// InvalidateLayout es redundante aqu\xed: RecalculateSize ya lo dispara',
     '// InvalidateLayout is redundant here: RecalculateSize already triggers it'),
    (r'// Throttle: m\xe1ximo ~15 rec\xe1lculos/seg durante streaming\.',
     '// Throttle: max ~15 recalcs/sec during streaming.'),
    (r'// Guardar burbuja pendiente; encolar rec\xe1lculo diferido si no hay uno ya encolado',
     '// Save pending bubble; enqueue deferred recalc if none already enqueued'),
    (r'// de c\xf3digo en el formulario\. Las propiedades directas de TComponent resuelven',
     '// of code in the form. Direct TComponent properties resolve'),
    (r'// TPersistent\) no garantiza la resoluci\xf3n de referencias forward\.',
     '// TPersistent) does not guarantee forward reference resolution.'),
    (r'// Inyectar configuraci\xf3n del sanitizador',
     '// Inject sanitizer configuration'),
    (r'// Inyectar sub-objetos de par\xe1metros especiales',
     '// Inject special parameters sub-objects'),
    (r'// GetEnumValue es sensible a may\xfasculas seg\xfan el Enum definido en uMakerAi\.Core',
     '// GetEnumValue is case-sensitive according to the Enum defined in uMakerAi.Core'),
    (r'// Fallo silencioso por propiedad individual para no detener el resto de la inyecci\xf3n',
     '// Silent failure per property to not stop the rest of the injection'),
    (r'// Outer try: garantiza que ninguna excepci\xf3n \(ni siquiera del log\)',
     '// Outer try: guarantees no exception (not even from logging)'),
    (r'// Fallback: captura cualquier excepci\xf3n no prevista \(nunca debe llegar aqu\xed\)',
     '// Fallback: catches any unexpected exception (should never reach here)'),
    (r'// v2: tool_calls es un objeto \(no array\); index en nivel ra\xedz identifica la posici\xf3n',
     '// v2: tool_calls is an object (not array); index at root level identifies the position'),
    (r'// Usamos index del nivel ra\xedz para localizar el tool call iniciado previamente',
     '// Use root level index to locate the previously initiated tool call'),
    (r'// v2: citations es un objeto \(no array\); index en nivel ra\xedz identifica la posici\xf3n',
     '// v2: citations is an object (not array); index at root level identifies the position'),
    (r'// Resetear antes de cada nueva petici\xf3n',
     '// Reset before each new request'),
    (r'// Maneja SSE delta y \[DONE\] con reconstrucci\xf3n de tool_calls\.',
     '// Handles SSE delta and [DONE] with tool_calls reconstruction.'),
    (r'// ParseChat \(rama else\) ya dispar\xf3 FOnReceiveDataEnd y DoStateChange\(acsFinished\)\.',
     '// ParseChat (else branch) already fired FOnReceiveDataEnd and DoStateChange(acsFinished).'),
    (r'// Solo agregamos TempMsg al historial si no est\xe1 ya \(RunNew async no lo agrega\)\.',
     '// Only add TempMsg to history if not already there (RunNew async does not add it).'),
    (r'// Tool calls: ParseChat ejecut\xf3 las herramientas y Self\.Run inici\xf3',
     '// Tool calls: ParseChat executed the tools and Self.Run initiated'),
    (r'// emitir\xe1 sus propios eventos \(SSE тЖТ \[DONE\] тЖТ FOnReceiveDataEnd\)\.',
     '// will emit its own events (SSE тЖТ [DONE] тЖТ FOnReceiveDataEnd).'),
    (r'// No ponemos FBusy=False aqu\xed: el segundo round sigue en vuelo',
     '// Do not set FBusy=False here: the second round is still in flight'),
    (r'// y lo marcar\xe1 como False cuando termine \(BLOQUE DEEPSEEK / \[DONE\]\)\.',
     '// and will mark it False when done (DEEPSEEK BLOCK / [DONE]).'),
    (r'// texto: todo termin\xf3',
     '// text: everything finished'),
    (r'// Limpiar para el pr\xf3ximo round o pr\xf3xima petici\xf3n',
     '// Clear for next round or next request'),
    (r'// CASO 2: JSON est\xe1ndar SSE con delta',
     '// CASE 2: Standard JSON SSE with delta'),
    (r'// respuesta llega como un objeto JSON completo \(no l\xedneas SSE con delta\)\.',
     '// response arrives as a complete JSON object (not SSE lines with delta).'),
    (r'// Tool calls: ParseChat ejecut\xf3 herramientas y Self\.Run inici\xf3',
     '// Tool calls: ParseChat executed tools and Self.Run initiated'),
    (r'// el segundo round async\. No disparar evento aqu\xed\.',
     '// the second async round. Do not trigger event here.'),
    (r'// FLUJO SSE EST\xc1NDAR \(stream=true, delta por l\xedneas\)',
     '// STANDARD SSE FLOW (stream=true, delta per line)'),
    (r'// 1\. Bucle principal: procesa l\xedneas completas terminadas en #10',
     '// 1. Main loop: processes complete lines ending in #10'),
    (r'// 2\. Borde de seguridad: \[DONE\] sin salto de l\xednea final',
     '// 2. Safety edge: [DONE] without final line break'),
    (r'// 4\. TOOLS \(Validaci\xf3n Estricta\)',
     '// 4. TOOLS (Strict Validation)'),
    (r'// B\. Code Execution \(Solo si est\xe1 expl\xedcitamente en el Set\)',
     '// B. Code Execution (Only if explicitly in the Set)'),
    (r'// C\. Google Search \(Solo si est\xe1 expl\xedcitamente en el Set\)',
     '// C. Google Search (Only if explicitly in the Set)'),
    (r'// La documentaci\xf3n especifica el entorno\.',
     '// The documentation specifies the environment.'),
    (r'// Usaremos \'only_name\' si la API lo infiere, pero mejor ser expl\xedcitos\.',
     '// We will use \'only_name\' if the API infers it, but better be explicit.'),
    (r'// Nota: Si quieres excluir acciones \(como drag_and_drop\), se configuran aqu\xed\.',
     '// Note: If you want to exclude actions (like drag_and_drop), configure them here.'),
    (r'// Por ahora enviamos el objeto vac\xedo o con configuraci\xf3n m\xednima si es necesario\.',
     '// For now we send the empty object or with minimal configuration if needed.'),
    (r'// A\. Par\xe1metros Est\xe1ndar \(No perder funcionalidad b\xe1sica\)',
     '// A. Standard Parameters (Do not lose basic functionality)'),
    (r'// B\. Configuraci\xf3n de Imagen \(Gemini 3 Image / Imagen 3\)',
     '// B. Image Configuration (Gemini 3 Image / Imagen 3)'),
    (r'// Gemini 2\.5 y anteriores: usar thinkingBudget num\xe9rico',
     '// Gemini 2.5 and earlier: use numeric thinkingBudget'),
    (r'// Safety: Gemini suele requerir un m\xednimo \(ej\. 1024\) para pensar efectivamente',
     '// Safety: Gemini usually requires a minimum (e.g. 1024) to think effectively'),
    (r'// Solo a\xf1adimos budget si es mayor a 0 \(0 deshabilita thinking en Flash 2\.5\)',
     '// Only add budget if greater than 0 (0 disables thinking in Flash 2.5)'),
    (r'// Si el archivo NO es imagen ni audio, y a\xfan no tiene URL de nube\.\.\.',
     '// If file is NOT image nor audio, and still has no cloud URL...'),
    (r'// 2\. Extracci\xf3n de Metadatos Generales',
     '// 2. General Metadata Extraction'),
    (r'// \[V3\] Token count espec\xedfico para pensamientos',
     '// [V3] Token count specific for thoughts'),
    (r'// 4\. Procesar Grounding \(B\xfasqueda Web\)',
     '// 4. Process Grounding (Web Search)'),
    (r'// B\. Code Execution: C\xf3digo generado \(Historial\)',
     '// B. Code Execution: Generated Code (History)'),
    (r'// D\. Multimedia Inline \(Im\xe1genes/Audio generados\)',
     '// D. Inline Multimedia (Generated Images/Audio)'),
    (r'// Determinar extensi\xf3n usando la funci\xf3n central de MimeType->Ext',
     '// Determine extension using the central MimeType->Ext function'),
    (r'// Si se solicit\xf3 extracci\xf3n de archivos de texto \(native output\)',
     '// If text file extraction was requested (native output)'),
    (r'// Acumulamos el texto\. Nota: Si ya tra\xeda algo \(streaming\), concatenamos o seteamos\.',
     '// We accumulate the text. Note: If it already had something (streaming), we concatenate or set.'),
    (r'// En ParseChat normal \(s\xedncrono o final de async\), Prompt suele estar vac\xedo al inicio del parseo de este frame\.',
     '// In normal ParseChat (sync or async end), Prompt is usually empty at the start of parsing this frame.'),
    (r'// CASO 2: HAY FUNCIONES \(EJECUCI\xd3N DE HERRAMIENTAS\)',
     '// CASE 2: THERE ARE FUNCTIONS (TOOL EXECUTION)'),
    (r'// GetMessages lo detectar\xe1 y NO lo volver\xe1 a envolver gracias a la correcci\xf3n\.',
     '// GetMessages will detect it and NOT wrap it again thanks to the fix.'),
    (r'// M\xfaltiples funciones: usamos gemini_parts',
     '// Multiple functions: use gemini_parts'),
    (r'// Pero en el flujo de herramientas, \'ResMsg\' se recicla para el resultado final de la recursi\xf3n\.',
     '// But in the tool flow, \'ResMsg\' is recycled for the final recursion result.'),
    (r'// El mensaje que contiene la llamada a la funci\xf3n \(y por tanto la firma\) es \'Msg\'\.',
     '// The message containing the function call (and therefore the signature) is \'Msg\'.'),
    (r'// Lo quitamos del diccionario sin liberarlo \(porque usamos ExtractPair impl\xedcito al reasignar propiedad o manual\)',
     '// Remove from dictionary without freeing (because we use implicit ExtractPair when reassigning property or manual)'),
    (r'// Archivos devueltos por el tool MCP \(im\xe1genes, PDFs\) тЖТ ToolMsg para que el LLM los vea',
     '// Files returned by MCP tool (images, PDFs) тЖТ ToolMsg so the LLM can see them'),
    (r'// El resultado final llenar\xe1 \'ResMsg\' correctamente\.',
     '// The final result will fill \'ResMsg\' correctly.'),
    (r'// Limpieza cosm\xe9tica: A veces la recursi\xf3n a\xf1ade el texto al final,',
     '// Cosmetic cleanup: Sometimes recursion adds text at the end,'),
    (r'// \[V3 UPDATE\] Helpers para conversi\xf3n de enums',
     '// [V3 UPDATE] Helpers for enum conversion'),
    (r'// Parsear groundingSupports \(v\xednculos texto->fuente\)',
     '// Parse groundingSupports (text->source links)'),
    (r'// M\xe9todos de Cache existentes \(RetrieveCache, DeleteCache, ListCaches\)\.\.\.',
     '// Existing Cache methods (RetrieveCache, DeleteCache, ListCaches)...'),
    (r'// A\xf1adir en la secci\xf3n Private o Protected de la clase',
     '// Add in the Private or Protected section of the class'),
    (r'// Ya se proces\xf3',
     '// Already processed'),
    (r'// Solo procesar si el usuario lo configur\xf3 en NativeOutputFiles',
     '// Only process if user configured it in NativeOutputFiles'),
    (r'// Intentar dar un nombre l\xf3gico',
     '// Try to give a logical name'),
    (r'// \[M\xe9todos de archivo \(UploadFile, etc\.\) se mantienen igual\]',
     '// [File methods (UploadFile, etc.) remain the same]'),
    (r'// 1\. Verificar si ComputerUse est\xe1 activo y tenemos el componente enlazado',
     '// 1. Check if ComputerUse is active and we have the component linked'),
    (r'// Como estamos dentro de un TTask \(hilo\), el evento OnExecuteAction se disparar\xe1 en un hilo secundario\.',
     '// Since we are inside a TTask (thread), the OnExecuteAction event will fire in a secondary thread.'),
    (r'// Aseg\xfarate de usar TThread\.Synchronize en tu formulario si tocas la GUI\.',
     '// Make sure to use TThread.Synchronize in your form if you touch the GUI.'),
    (r'// 4\. Si no es acci\xf3n de computadora, usar el comportamiento est\xe1ndar \(AiFunctions o Evento\)',
     '// 4. If not a computer action, use standard behavior (AiFunctions or Event)'),
    (r'// Implementaci\xf3n basada en predictLongRunning y Polling',
     '// Implementation based on predictLongRunning and Polling'),
    (r'// Preferir URI si ya est\xe1 subido \(File API\), si no, usar Base64 \(para im\xe1genes peque\xf1as\)',
     '// Prefer URI if already uploaded (File API), otherwise use Base64 (for small images)'),
    (r'// 3\. Construir "parameters" \(Configuraci\xf3n de Veo\)',
     '// 3. Build "parameters" (Veo Configuration)'),
    (r'// Iterar par\xe1metros definidos por el usuario en el componente',
     '// Iterate user-defined parameters in the component'),
    (r'// L\xf3gica espec\xedfica para strings de Veo que NO deben ser n\xfameros',
     '// Specific logic for Veo strings that should NOT be numbers'),
    (r'// Detecci\xf3n de tipos para el resto \(seed, durationSeconds, etc\)',
     '// Type detection for the rest (seed, durationSeconds, etc)'),
    (r'// 4\. Enviar Petici\xf3n Inicial',
     '// 4. Send Initial Request'),
    (r'// 5\. Obtener Operation Name \(ID de la tarea de larga duraci\xf3n\)',
     '// 5. Get Operation Name (long-running task ID)'),
    (r'// La URL de polling es base + nombre de operaci\xf3n',
     '// Polling URL is base + operation name'),
    (r'// 6\. Iniciar Tarea As\xedncrona de Polling',
     '// 6. Start Async Polling Task'),
    (r'// Verificar si termin\xf3 \("done": true\)',
     '// Check if finished ("done": true)'),
    (r'// Clonar respuesta final porque TaskPollingResponse se liberar\xe1',
     '// Clone final response because TaskPollingResponse will be freed'),
    (r'// Verificar errores devueltos por la operaci\xf3n',
     '// Check errors returned by the operation'),
    (r'// --- CORRECCI\xd3N AQU\xcd ---',
     '// --- CORRECTION HERE ---'),
    (r'// Asignar Stream y MimeType es importante para que el componente visual sepa qu\xe9 es',
     '// Assigning Stream and MimeType is important so the visual component knows what it is'),
    (r'// Ahora ver\xe1s el mensaje de error real si falla de nuevo',
     '// Now you will see the real error message if it fails again'),
    (r'// Dictionary que es due\xf1o de los MediaFiles \(los libera autom\xe1ticamente\)',
     '// Dictionary that owns the MediaFiles (frees them automatically)'),
    (r'// Notificaci\xf3n final',
     '// Final notification'),
    (r'// El TTask se ejecutar\xe1 en segundo plano y notificar\xe1 v\xeda eventos\.',
     '// The TTask will run in the background and notify via events.'),
    (r'// Voz por defecto \'Puck\' si no hay configuraci\xf3n',
     '// Default voice \'Puck\' if no configuration'),
    (r'// RAMA AS\xcdNCRONA: lanza TTask y retorna inmediatamente',
     '// ASYNC BRANCH: launches TTask and returns immediately'),
    (r'// Crear un ResMsg propio y a\xf1adirlo a FMessages ANTES de lanzar la tarea\.',
     '// Create our own ResMsg and add it to FMessages BEFORE launching the task.'),
    (r'// Esto es imprescindible porque Run\(\) liberar\xe1 el ResMsg que nos pas\xf3',
     '// This is essential because Run() will free the ResMsg passed to us'),
    (r'// \(LOwnsResMsg=True\) justo despu\xe9s de que retornemos\. Si us\xe1ramos ese',
     '// (LOwnsResMsg=True) right after we return. If we used that'),
    (r'// mismo puntero en el TTask, acceder\xedamos a memoria liberada\.',
     '// same pointer in the TTask, we would access freed memory.'),
    (r'// M\xe9todos Batch \(CreateBatchJob, GetBatchJob\)',
     '// Batch methods (CreateBatchJob, GetBatchJob)'),
    (r'// Notificar \xe9xito en el hilo principal',
     '// Notify success in the main thread'),
    (r'// RAMA S\xcdNCRONA: comportamiento original \(bloquea hasta tener el audio\)',
     '// SYNC BRANCH: original behavior (blocks until audio is obtained)'),
    (r'// Forzar modo s\xedncrono en FClient y restaurar despu\xe9s',
     '// Force sync mode in FClient and restore after'),
    (r'// Convertir a WAV \(24kHz, Mono, 16bit тАФ est\xe1ndar Gemini TTS\)',
     '// Convert to WAV (24kHz, Mono, 16bit тАФ Gemini TTS standard)'),
    (r'// \[V3 UPDATE\] Implementaci\xf3n de Image Generation espec\xedfica para V3 \(si es diferente\)',
     '// [V3 UPDATE] Image Generation implementation specific for V3 (if different)'),
    (r'// Como el m\xe9todo InternalRunImageGeneration actualmente deriva a Completions,',
     '// Since the InternalRunImageGeneration method currently derives to Completions,'),
    (r'// pero aqu\xed a\xf1adimos soporte b\xe1sico si el modelo es gemini-3-pro-image-preview\.',
     '// but here we add basic support if the model is gemini-3-pro-image-preview.'),
    (r'// Variables para la l\xf3gica de finalizaci\xf3n',
     '// Variables for completion logic'),
    (r'// 1\. LECTURA DEL STREAM Y ACUMULACI\xd3N EN BUFFER',
     '// 1. STREAM READING AND BUFFER ACCUMULATION'),
    (r'// Break; // Esperar m\xe1s datos o buffer vac\xedo',
     '// Break; // Wait for more data or empty buffer'),
    (r'// Debemos ignorar llaves {} que est\xe1n dentro de cadenas \(Quotes\)',
     '// We must ignore {} braces that are inside strings (Quotes)'),
    (r'// Detectar escape para la siguiente iteraci\xf3n \(ej: \\\\"\)',
     '// Detect escape for next iteration (e.g. \\\\")'),
    (r'// C\. Extracci\xf3n y Parseo Seguro',
     '// C. Safe Extraction and Parsing'),
    (r'// Intentamos parsear\. Si falla, podr\xeda ser un JSON malformado, pero asumimos que Gemini env\xeda bien\.',
     '// We try to parse. If it fails, it could be malformed JSON, but we assume Gemini sends correctly.'),
    (r'// Lo importante es NO borrar del buffer hasta confirmar que parse\xf3 bien\.',
     '// The important thing is NOT to delete from buffer until confirmed it parsed well.'),
    (r'// Raro: Estructura parec\xeda bien balanceada pero fall\xf3 el parseo\.',
     '// Rare: Structure seemed well balanced but parsing failed.'),
    (r'// En este caso, asumimos corrupci\xf3n y avanzamos para no colgar el bucle\.',
     '// In this case, we assume corruption and advance to not hang the loop.'),
    (r'// PARSEO EXITOSO: Ahora s\xed borramos del buffer',
     '// PARSE SUCCESSFUL: Now we delete from buffer'),
    (r'// 1\. Detecci\xf3n de Finalizaci\xf3n \(FinishReason\)',
     '// 1. Completion Detection (FinishReason)'),
    (r'// 3\. FINALIZACI\xd3N IN-PLACE',
     '// 3. IN-PLACE COMPLETION'),
    (r'// Aqu\xed ejecutamos lo que antes hac\xeda InternalCompleteRequest',
     '// Here we execute what InternalCompleteRequest did before'),
    (r'// --- RECONSTRUCCI\xd3N DEL HISTORIAL \(GEMINI PARTS / FIRMAS\) ---',
     '// --- HISTORY RECONSTRUCTION (GEMINI PARTS / SIGNATURES) ---'),
    (r'// Actualizaci\xf3n: Integraci\xf3n API Gemini 3 \(Thinking Level, Signatures, Media Resolution\)',
     '// Update: Gemini 3 API Integration (Thinking Level, Signatures, Media Resolution)'),
    (r'// RECURSI\xd3N',
     '// RECURSION'),
    (r'// FINALIZAR: Cortar conexi\xf3n HTTP',
     '// FINALIZE: Cut HTTP connection'),
    (r'// Si ya se proces\xf3 el final en el stream \(finishReason detectado\), FBusy ser\xe1 False\.',
     '// If the end was already processed in the stream (finishReason detected), FBusy will be False.'),
    (r'// Si llegamos aqu\xed, el stream termin\xf3 HTTP-wise pero no detectamos finishReason antes\.',
     '// If we reach here, the stream ended HTTP-wise but we did not detect finishReason before.'),
    (r'// Llamamos al padre por si acaso tiene l\xf3gica gen\xe9rica',
     '// Call parent in case it has generic logic'),
    (r'// Limpiar entradas vac\xedas',
     '// Clean empty entries'),
    (r'// CASO A: M\xdaLTIPLES VOCES \(> 1 elemento\) -> MULTI-SPEAKER',
     '// CASE A: MULTIPLE VOICES (> 1 element) -> MULTI-SPEAKER'),
    (r'// --- NUEVA L\xd3GICA DE PARSEO MANUAL \(M\xc1S SEGURA\) ---',
     '// --- NEW MANUAL PARSING LOGIC (SAFER) ---'),
    (r'// Encontr\xf3 el \'=\', separamos:',
     '// Found \'=\', we separate:'),
    (r'// Voice: desde despu\xe9s del \'=\' hasta el final',
     '// Voice: from after \'=\' to the end'),
    (r'// Parseo manual tambi\xe9n aqu\xed para limpiar "Gustavo=Puck" -> "Puck"',
     '// Manual parsing here too to clean "Gustavo=Puck" -> "Puck"'),
    (r'// Variables para gesti\xf3n de firmas V3',
     '// Variables for V3 signatures management'),
    (r'// --- CORRECCI\xd3N JSON RESPONSE ---',
     '// --- JSON RESPONSE CORRECTION ---'),
    (r'// Si el mensaje es un JSON v\xe1lido \(como el que devuelve ComputerUseTool\)',
     '// If the message is valid JSON (like the one returned by ComputerUseTool)'),
    (r'// Si es texto plano o inv\xe1lido, usamos la estructura legacy envolvente',
     '// If plain text or invalid, use the legacy wrapper structure'),
    (r'// Usamos \'content\' o \'result\' seg\xfan prefieras para texto plano,',
     '// Use \'content\' or \'result\' as preferred for plain text,'),
    (r'// pero ComputerUse siempre entrar\xe1 en el IF de arriba\.',
     '// but ComputerUse will always enter the IF above.'),
    (r'// Nuevo helper para agregar firmas f\xe1cilmente',
     '// New helper to add signatures easily'),
    (r'// --- CORRECCI\xd3N CR\xcdTICA AQU\xcd ---',
     '// --- CRITICAL CORRECTION HERE ---'),
    (r'// Si esta parte es un archivo binario \(inlineData\), NO la agregamos al historial de env\xedo\.',
     '// If this part is a binary file (inlineData), do NOT add it to the send history.'),
    (r'// El modelo ya sabe que gener\xf3 el archivo, no necesitamos devolverle los bytes\.',
     '// The model already knows it generated the file, we do not need to return the bytes.'),
    (r'// Variables para extracci\xf3n de par\xe1metros',
     '// Variables for parameter extraction'),
    (r'// --- BUCLE DE PAGINACI\xd3N ---',
     '// --- PAGINATION LOOP ---'),
    (r'// 2\. Construir URL con el token de p\xe1gina si existe',
     '// 2. Build URL with page token if exists'),
    (r'// 3\. Petici\xf3n GET',
     '// 3. GET Request'),
    (r'// A\. Procesar Modelos de esta p\xe1gina',
     '// A. Process Models on this page'),
    (r'// --- EXTRACCI\xd3N DE VARIABLES ---',
     '// --- VARIABLE EXTRACTION ---'),
    (r'// 1\. Datos B\xe1sicos',
     '// 1. Basic Data'),
    (r'// --- FILTRADO DE M\xc9TODOS ---',
     '// --- METHOD FILTERING ---'),
    (r'// ACEPTAMOS M\xc1S M\xc9TODOS AHORA:',
     '// ACCEPTING MORE METHODS NOW:'),
    (r'// B\. Agregar si es v\xe1lido',
     '// B. Add if valid'),
    (r'// C\. Obtener el Token para la siguiente p\xe1gina \(si hay\)',
     '// C. Get Token for next page (if any)'),
    (r'// Error de conexi\xf3n, rompemos el bucle',
     '// Connection error, break the loop'),
    (r'// Repetir mientras haya m\xe1s p\xe1ginas',
     '// Repeat while there are more pages'),
    (r'// 1\. CONTEXTO Y CACH\xc9',
     '// 1. CONTEXT AND CACHE'),
    (r'// local, no se requiere autenticaci\xf3n',
     '// local, no authentication required'),
    (r'// Permite usar m\xfaltiples instancias de TAiGenericChat apuntando a APIs distintas\.',
     '// Allows using multiple TAiGenericChat instances pointing to different APIs.'),
    (r'// Respuestas API de xAI para b\xfasqueda web',
     '// xAI API responses for web search'),
    (r'// ------- Gemma 4 \(vision \+ audio \+ reasoning nativo, tama\xf1os: e4b / 4b / 12b / 27b\) ------',
     '// ------- Gemma 4 (native vision + audio + reasoning, sizes: e4b / 4b / 12b / 27b) ------'),
    (r'// Nota: no soporta ThinkingLevel \(INVALID_ARGUMENT si se env\xeda\)',
     '// Note: does not support ThinkingLevel (INVALID_ARGUMENT if sent)'),
    (r'// Si la Fase 1 \(InternalRunPDFDescription\) ya ejecut\xf3 el OCR con \xe9xito',
     '// If Phase 1 (InternalRunPDFDescription) already executed OCR successfully'),
    (r'// Arguments contiene el JSON can\xf3nico de par\xe1metros',
     '// Arguments contains the canonical JSON of parameters'),
    (r'// Si no hay par\xe1metros no marca error',
     '// If no parameters, do not mark error'),
    (r'// Hacemos la llamada s\xedncrona, pero Ollama devuelve el stream completo de una vez',
     '// We make the sync call, but Ollama returns the complete stream at once'),
    (r'// Si el evento de progreso est\xe1 asignado, lo disparamos',
     '// If the progress event is assigned, fire it'),
    (r'// TryGetValue es m\xe1s seguro si los campos no siempre est\xe1n presentes',
     '// TryGetValue is safer if fields are not always present'),
    (r'// Ollama ahora s\xed incluye un \'id\', pero lo generamos como fallback por si acaso\.',
     '// Ollama now includes an \'id\', but we generate it as fallback just in case.'),
    (r'// Im\xe1genes y audio se env\xedan ambos en el campo \'images\' en base64\.',
     '// Images and audio are both sent in the \'images\' field in base64.'),
    (r'// 1\. Configuraci\xf3n b\xe1sica y Modelo',
     '// 1. Basic configuration and Model'),
    (r'// Configuramos el cliente HTTP seg\xfan la propiedad del componente',
     '// Configure HTTP client according to component property'),
    (r'// Objeto para par\xe1metros avanzados',
     '// Object for advanced parameters'),
    (r'// --- PAR\xc1METROS RA\xcdZ ---',
     '// --- ROOT PARAMETERS ---'),
    (r'// Usa GetMessages \(revisaremos este despu\xe9s\)',
     '// Uses GetMessages (we will review this later)'),
    (r'// Respetamos la configuraci\xf3n as\xedncrona \(True/False\)',
     '// Respect async configuration (True/False)'),
    (r'// Ollama espera el esquema DIRECTAMENTE en el par\xe1metro "format"\.',
     '// Ollama expects the schema DIRECTLY in the "format" parameter.'),
    (r'// Si no es un objeto v\xe1lido, limpiar',
     '// If not a valid object, clean'),
    (r'// Manejo silencioso de errores de parseo, se enviar\xe1 sin formato o ignorado',
     '// Silent handling of parse errors, will send without format or ignored'),
    (r'// --- PAR\xc1METROS "OPTIONS" \(Diferencia clave con OpenAI\)',
     '// --- "OPTIONS" PARAMETERS (Key difference with OpenAI)'),
    (r'// Ollama requiere encapsular estos par\xe1metros dentro de \'options\'',
     '// Ollama requires encapsulating these parameters inside \'options\''),
    (r'// Si no se a\xf1adi\xf3 al padre, hay que liberarlo',
     '// If not added to parent, must free it'),
    (r'// Generaci\xf3n del String final',
     '// Generation of final String'),
    (r'// jOptions se libera autom\xe1ticamente si fue a\xf1adido a AJSONObject',
     '// jOptions is freed automatically if added to AJSONObject'),
    (r'// Esto no funciona en multiarea, as\xed que se libera cuando no lo es\.',
     '// This does not work in multiarea, so it is freed when it is not.'),
    (r'// Limpieza de buffers para la siguiente petici\xf3n',
     '// Clean buffers for next request'),
    (r'// --- Bucle principal para procesar l\xedneas \(Ollama env\xeda un JSON por l\xednea\) ---',
     '// --- Main loop to process lines (Ollama sends one JSON per line) ---'),
    (r'// --- MANEJO DE FRAGMENTO FINAL \(sin salto de l\xednea\) ---',
     '// --- FINAL FRAGMENT HANDLING (no line break) ---'),
    (r'// ----- FUNCIONES DE GESTI\xd3N DE MODELOS  -----------',
     '// ----- MODEL MANAGEMENT FUNCTIONS  -----------'),
    (r'// 1\. EXTRAER METADATOS Y ESTAD\xcdSTICAS',
     '// 1. EXTRACT METADATA AND STATISTICS'),
    (r'// Ollama usa nombres espec\xedficos para los tokens',
     '// Ollama uses specific names for tokens'),
    (r'// Si no hay mensaje pero el JSON indica que termin\xf3, disparamos el evento de fin',
     '// If no message but JSON indicates finished, fire the end event'),
    (r'// 4\. L\xd3GICA DE LLAMADO A FUNCIONES \(TOOLS\)',
     '// 4. FUNCTION CALLING LOGIC (TOOLS)'),
    (r'// A\.1 Guardamos el mensaje del asistente \(la petici\xf3n de tool\) en el historial',
     '// A.1 Save the assistant message (the tool request) in history'),
    (r'// A\.3 Ejecuci\xf3n en paralelo de las funciones encontradas',
     '// A.3 Parallel execution of found functions'),
    (r'// A\.4 A\xf1adir los resultados de las funciones \(role: tool\) al historial',
     '// A.4 Add function results (role: tool) to history'),
    (r'// B\.1 Extracci\xf3n autom\xe1tica de bloques de c\xf3digo si se solicita',
     '// B.1 Automatic extraction of code blocks if requested'),
    (r'// Cargamos el c\xf3digo extra\xeddo como un archivo adjunto al mensaje',
     '// Load extracted code as an attachment to the message'),
    (r'// B\.3 Gesti\xf3n del historial \(Evitar Doble Add en As\xedncrono\)',
     '// B.3 History management (Avoid Double Add in Async)'),
    (r'// En s\xedncrono, TAiChat\.Run a\xf1ade el mensaje al finalizar\.',
     '// In sync, TAiChat.Run adds the message at the end.'),
    (r'// En as\xedncrono, como el Run ya sali\xf3, debemos a\xf1adirlo aqu\xed\.',
     '// In async, since Run already exited, we must add it here.'),
    (r'// B\.4 Finalizaci\xf3n y notificaci\xf3n a la UI',
     '// B.4 Completion and UI notification'),
    (r'// C\) INFORMACI\xd3N de finalizaci\xf3n \(Finish Reason / Incomplete Details\)',
     '// C) COMPLETION INFO (Finish Reason / Incomplete Details)'),
    (r'// incomplete_details ausente o null: si el estado es completed, finalizaci\xf3n normal',
     '// incomplete_details absent or null: if status is completed, normal completion'),
    (r'// --- 2\. EJECUCI\xd3N DE LA PETICI\xd3N POST ---',
     '// --- 2. POST REQUEST EXECUTION ---'),
    (r'// Inicia una nueva conversaci\xf3n',
     '// Starts a new conversation'),
    (r'// doOwnsValues libera BufferTool autom\xe1ticamente',
     '// doOwnsValues frees BufferTool automatically'),
    (r'// Archivos adjuntos \(im\xe1genes/PDFs devueltos por el tool MCP\)',
     '// Attached files (images/PDFs returned by MCP tool)'),
    (r'// mensaje user separado, inmediatamente despu\xe9s del tool result\.',
     '// separate user message, immediately after the tool result.'),
    (r'// vac\xedo, no se usa',
     '// empty, not used'),
    (r'// razonamiento contenido requerido por APIs como DeepSeek y Kimi cuando thinking est\xe1 habilitado\.',
     '// reasoning_content required by APIs like DeepSeek and Kimi when thinking is enabled.'),
    (r'// reasoning_content requerido por APIs como DeepSeek y Kimi cuando thinking est\xe1 habilitado\.',
     '// reasoning_content required by APIs like DeepSeek and Kimi when thinking is enabled.'),
    (r'// Solo se serializa cuando est\xe1 presente \(no afecta a providers que no lo usan\)\.',
     '// Only serialized when present (does not affect providers that do not use it).'),
    (r'// Archivos extra\xeddos por el tool \(ej: im\xe1genes devueltas por MCP\)',
     '// Files extracted by the tool (e.g. images returned by MCP)'),
    (r'// Limpiar para el pr\xf3ximo round o pr\xf3xima petici\xf3n',
     '// Clear for next round or next request'),
    (r'// Anthropic env\xeda \{"type":"error","error":\{"type":"rate_limit_error","message":"\.\.\."\}\}',
     '// Anthropic sends {"type":"error","error":{"type":"rate_limit_error","message":"..."}}'),
    (r'// guard: evitar doble-add \(ej: Cohere ParseChat ya lo agreg\xf3\)',
     '// guard: avoid double-add (e.g. Cohere ParseChat already added it)'),
    (r'// respuesta de tool no se agrega al historial: liberar si somos due\xf1os',
     '// tool response not added to history: free if we are owners'),
    (r'// contin\xfaa sin modificar el prompt',
     '// continues without modifying the prompt'),
    (r'// Extensi\xf3n para drivers con delta\.content como array tipado \(ej: Mistral magistral\)\.',
     '// Extension for drivers with delta.content as typed array (e.g. Mistral magistral).'),
    (r'// La base no hace nada; los drivers con formato no-est\xe1ndar lo sobreescriben\.',
     '// Base does nothing; drivers with non-standard format override it.'),
    (r'// configuraci\xf3n unificada del modelo \(v3\.3\)',
     '// unified model configuration (v3.3)'),
    (r'// que FOwner sea destruido\. Si no, SpeechTool\.FFreeNotifies quedar\xe1 con un',
     '// that FOwner is destroyed. If not, SpeechTool.FFreeNotifies will be left with a'),
    (r'// puntero colgante y llamar\xe1 Notification sobre memoria liberada тЖТ AV\.',
     '// dangling pointer and will call Notification on freed memory тЖТ AV.'),
    (r'// Evento para que el desarrollador apruebe o deniegue la instalaci\xf3n de un paquete MCP v\xeda AutoMCP\.',
     '// Event for the developer to approve or deny installation of an MCP package via AutoMCP.'),
    (r'\(Gemini, OpenAI, Claude, Ollama\) requieren base64 sin saltos de l\xednea\.',
     '(Gemini, OpenAI, Claude, Ollama) require base64 without line breaks.'),
    (r'// Extensi\xf3n para drivers con delta\.content como array tipado \(ej: Mistral magistral\)\.',
     '// Extension for drivers with delta.content as typed array (e.g. Mistral magistral).'),
    (r'// Agrupa todas las herramientas \(tools\) del chat en un \xfanico objeto persistente\.',
     '// Groups all chat tools in a single persistent object.'),
    (r'// pueden tardar mucho m\xe1s que el handshake de inicializaci\xf3n\.',
     '// may take much longer than the initialization handshake.'),
    (r'// M\xednimo 60s; si el par\xe1metro Timeout est\xe1 configurado m\xe1s alto, usarlo\.',
     '// Minimum 60s; if Timeout parameter is configured higher, use it.'),
    (r'// Desconecta el servidor \(conexi\xf3n persistente Opci\xf3n D\)\. Llamar para',
     '// Disconnects the server (persistent connection Option D). Call to'),
    (r'// Detiene el proceso servidor y libera la conexi\xf3n persistente',
     '// Stops the server process and releases the persistent connection'),
    (r'// Implementaci\xf3n base vac\xeda: las subclases con conexi\xf3n persistente la sobreescriben',
     '// Empty base implementation: subclasses with persistent connection override it'),
    (r'// La conexi\xf3n persistente se cierra aqu\xed autom\xe1ticamente\.',
     '// The persistent connection closes here automatically.'),
    (r'// --- M\xe9todos de Ciclo de Vida Completo ---',
     '// --- Full Lifecycle Methods ---'),
    (r'// --- Opci\xf3n D: conexi\xf3n persistente StdIo ---',
     '// --- Option D: persistent StdIo connection ---'),
    (r'// ListTools y CallTool reutilizan la conexi\xf3n existente si est\xe1 disponible\.',
     '// ListTools and CallTool reuse existing connection if available.'),
    (r'//   - El servidor se inicia autom\xe1ticamente en la primera llamada a ListTools o CallTool\.',
     '//   - Server starts automatically on first ListTools or CallTool call.'),
    (r'//   - Permanece activo para reutilizar la conexi\xf3n en llamadas siguientes\.',
     '//   - Remains active to reuse connection in subsequent calls.'),
    (r'//   - Se detiene autom\xe1ticamente al destruir el componente \(no hace falta llamar Disconnect\)\.',
     '//   - Stops automatically when component is destroyed (no need to call Disconnect).'),
    (r'//   - Llamar Disconnect\(\) expl\xedcitamente solo si se quiere liberar el proceso antes de destruir\.',
     '//   - Call Disconnect() explicitly only if you want to free the process before destroying.'),
    (r'// Si el servidor ya est\xe1 corriendo reutilizamos la conexi\xf3n',
     '// If server is already running we reuse the connection'),
    (r'// Pausa para que el servidor procese la notificaci\xf3n',
     '// Pause for server to process the notification'),
    (r'// ParseChat lanza m\xfaltiples TTask con herramientas del mismo servidor MCP\)\.',
     '// ParseChat launches multiple TTask with tools from the same MCP server).'),
    (r'// Llamar a la versi\xf3n principal, que ahora es due\xf1a de ArgsObject',
     '// Call the main version, which now owns ArgsObject'),
    (r'// FIsRunning=True y FReadThread/FInteractiveProcess asignados pero inv\xe1lidos\.',
     '// FIsRunning=True and FReadThread/FInteractiveProcess assigned but invalid.'),
    (r'// Invocar Stop garantiza liberaci\xf3n antes de crear objetos nuevos\.',
     '// Calling Stop guarantees release before creating new objects.'),
    (r'// Salida r\xe1pida solo si ya estamos completamente detenidos \(todos los campos limpios\)\.',
     '// Fast exit only if already completely stopped (all fields clean).'),
    (r'// NO usar IsServerRunning aqu\xed: si el proceso muri\xf3 de forma inesperada,',
     '// Do NOT use IsServerRunning here: if the process died unexpectedly,'),
    (r'// CR\xcdTICO: secuencia correcta para evitar AV por race condition\.',
     '// CRITICAL: correct sequence to avoid AV due to race condition.'),
    (r'// thread ya sali\xf3 \(pipe cerrado \+ FIsRunning=False\)',
     '// thread already exited (pipe closed + FIsRunning=False)'),
    (r'// Ahora s\xed es seguro liberar el objeto del proceso',
     '// Now it is safe to free the process object'),
    (r'// Clonamos el resultado para que el llamador sea el due\xf1o',
     '// Clone the result so the caller is the owner'),
    (r'// Layer 1: Validaci\xf3n de API Key',
     '// Layer 1: API Key Validation'),
    (r'// Layer 2: Evento de validaci\xf3n custom \(JWT, OAuth, DB lookup, etc\)\)',
     '// Layer 2: Custom validation event (JWT, OAuth, DB lookup, etc.)'),
    (r'// Lo hacemos protected para que los descendientes puedan acceder a \xe9l directamente\.',
     '// Make it protected so descendants can access it directly.'),
    (r'// Validaci\xf3n de requests: Layer 1 \(API Key\) \+ Layer 2 \(evento custom\)',
     '// Request validation: Layer 1 (API Key) + Layer 2 (custom event)'),
    (r'// Autenticaci\xf3n: Si ApiKey est\xe1 configurado, valida "Authorization: Bearer <key>" o "X-API-Key: <key>"',
     '// Authentication: If ApiKey is configured, validates "Authorization: Bearer <key>" or "X-API-Key: <key>"'),
    (r'// Evento custom para validaci\xf3n avanzada \(JWT, OAuth, DB lookup, etc\)\)',
     '// Custom event for advanced validation (JWT, OAuth, DB lookup, etc.)'),
    (r'// Evento de validaci\xf3n custom \(Layer 2\)\.',
     '// Custom validation event (Layer 2).'),
    (r'// AAuthContext: contexto de autenticaci\xf3n a poblar\.',
     '// AAuthContext: authentication context to populate.'),
    (r'// AIsValid: True si la petici\xf3n es v\xe1lida\.',
     '// AIsValid: True if the request is valid.'),
    (r'// Overload con AuthContext: usado por Http y SSE con autenticaci\xf3n',
     '// Overload with AuthContext: used by Http and SSE with authentication'),
    (r'// \xcdndice de offsets: compKey тЖТ TNodeFileEntry',
     '// Offsets index: compKey тЖТ TNodeFileEntry'),
    (r'// Reabrir y reconstruir \xedndices',
     '// Reopen and rebuild indices'),
    (r'// \xcdndices BM25: entidad тЖТ TAIBm25Index',
     '// BM25 indices: entity тЖТ TAIBm25Index'),
    (r'// Estad\xedsticas',
     '// Statistics'),
    (r'// B\xfasquedas individuales',
     '// Individual searches'),
    (r'// Fusi\xf3n',
     '// Fusion'),
    (r'// ---- Gesti\xf3n del archivo ----',
     '// ---- File management ----'),
    (r'// Actualizar idioma en todos los \xedndices BM25 existentes',
     '// Update language in all existing BM25 indices'),
    (r'// Helpers de clave compuesta y acceso a \xedndices',
     '// Composite key helpers and index access'),
    (r'// Reconstrucci\xf3n de \xedndices desde el archivo \(se llama en Open\)',
     '// Index reconstruction from file (called in Open)'),
    (r'// --- \xcdndice de offsets ---',
     '// --- Offsets index ---'),
    (r'// Reconstrucci\xf3n BM25 tras borrados \(solo en memoria, no releer disco\)',
     '// BM25 reconstruction after deletions (in memory only, no disk reread)'),
    (r'// Si ya existe, borrarlo primero \(sin reconstruir BM25 todav\xeda\)',
     '// If already exists, delete first (without rebuilding BM25 yet)'),
    (r'// Limpiar de \xedndices en memoria',
     '// Clean from memory indices'),
    (r'// No borrar de IDList aqu\xed тАФ lo reemplazaremos al agregar',
     '// Do not delete from IDList here тАФ will replace when adding'),
    (r'// Preparar embedding \(con padding si la dimensi\xf3n no coincide\)',
     '// Prepare embedding (with padding if dimension does not match)'),
    (r'// Actualizar \xedndice de offsets',
     '// Update offsets index'),
    (r'// Agregar stub al \xedndice BM25',
     '// Add stub to BM25 index'),
    (r'// Limpiar \xedndices',
     '// Clean indices'),
    (r'// Reconstruir BM25 solo para esta entidad \(en memoria, r\xe1pido\)',
     '// Rebuild BM25 only for this entity (in memory, fast)'),
    (r'// B\xfasqueda vectorial \(embeddings desde disco\)',
     '// Vector search (embeddings from disk)'),
    (r'// B\xfasqueda l\xe9xical BM25 \(completamente en memoria, stubs\)',
     '// Lexical BM25 search (completely in memory, stubs)'),
    (r'// Normalizar scores BM25 a \[0, 1\] usando el m\xe1ximo del conjunto',
     '// Normalize BM25 scores to [0, 1] using set maximum'),
    (r'// ya est\xe1 ordenado desc',
     '// already sorted desc'),
    (r'// Entrada del \xedndice de archivo: offsets para lectura eficiente',
     '// File index entry: offsets for efficient reading'),
    (r'// Fusi\xf3n RRF y ponderada',
     '// RRF and weighted fusion'),
    (r'// sqlite-vec fall\xf3 en runtime тЖТ fallback',
     '// sqlite-vec failed at runtime тЖТ fallback'),
    (r'// Fusi\xf3n',
     '// Fusion'),
    (r'// Ruta completa a sqlite_vec\.dll/\.so тАФ vac\xedo = modo Delphi \(brute-force cosine\)',
     '// Full path to sqlite_vec.dll/.so тАФ empty = Delphi mode (brute-force cosine)'),
    (r'// Aproximaci\xf3n: valor exacto en la clave indicada',
     '// Approximation: exact value at indicated key'),
    (r'// Gesti\xf3n del esquema',
     '// Schema management'),
    (r'// luego el INSERT dispara _ai тАФ as\xed FTS5 queda siempre consistente\.',
     '// then INSERT fires _ai тАФ thus FTS5 stays always consistent.'),
    (r'// B\xfasqueda vectorial тАФ similitud coseno en Delphi \(brute-force, O\(n\)\)',
     '// Vector search тАФ cosine similarity in Delphi (brute-force, O(n))'),
    (r'// Adecuado para colecciones peque\xf1as/medianas \(тЙд 50K nodos\)\.',
     '// Suitable for small/medium collections (тЙд 50K nodes).'),
    (r'// B\xfasqueda vectorial con sqlite-vec \(r\xe1pida, usa \xedndice vectorial nativo\)',
     '// Vector search with sqlite-vec (fast, uses native vector index)'),
    (r'// sqlite-vec almacena embeddings como BLOB; aqu\xed asumimos la columna',
     '// sqlite-vec stores embeddings as BLOB; here we assume the column'),
    (r'// la versi\xf3n TEXT con conversi\xf3n inline\.',
     '// the TEXT version with inline conversion.'),
    (r'// B\xfasqueda l\xe9xical BM25 v\xeda FTS5',
     '// Lexical BM25 search via FTS5'),
    (r'// FTS5 bm25\(\) devuelve valores тЙд 0 \(m\xe1s negativo = m\xe1s relevante\)\.',
     '// FTS5 bm25() returns values тЙд 0 (more negative = more relevant).'),
    (r'// Query FTS inv\xe1lida \(caracteres especiales sin escapar\) тАФ devolver vac\xedo',
     '// Invalid FTS query (special characters unescaped) тАФ return empty'),
    (r'// Primera pasada: recopilar candidatos y encontrar m\xe1ximo raw_score',
     '// First pass: collect candidates and find max raw_score'),
    (r'// evitar divisi\xf3n por cero',
     '// avoid division by zero'),
    (r'// temporal тАФ se normaliza despu\xe9s',
     '// temporal тАФ normalized later'),
    (r'// Fusi\xf3n RRF \(Reciprocal Rank Fusion\)',
     '// RRF Fusion (Reciprocal Rank Fusion)'),
    (r'// Copia un nodo creando una instancia nueva con misma dimensi\xf3n que ATarget',
     '// Copies a node creating a new instance with same dimension as ATarget'),
    (r'// Fusi\xf3n ponderada \(Weighted Score Fusion\)',
     '// Weighted Score Fusion'),
    (r'// Llamada directa siempre тАФ nunca TTask\.Run aqu\xed:',
     '// Direct call always тАФ never TTask.Run here:'),
    (r'//   Con TTask\.Run en sync mode, the caller le\xeda ResMsg\.Prompt vac\xedo y aMediaFile',
     '//   With TTask.Run in sync mode, the caller read ResMsg.Prompt empty and aMediaFile'),
    (r'//   pod\xeda liberarse antes de que el TTask terminara тЖТ access violation\.',
     '//   could be freed before the TTask finished тЖТ access violation.'),
    (r'//   asignaci\xf3n directa para que InternalRunTranscription lo lea en sync',
     '//   direct assignment so InternalRunTranscription reads it in sync'),
    (r'// Schema completo en JSON \(no descompuesto\)\. Cuando est\xe1 asignado,',
     '// Complete schema in JSON (not decomposed). When assigned,'),
    (r'// \xdatil para herramientas con schemas complejos \(anyOf, nested objects, etc\.\)',
     '// Useful for tools with complex schemas (anyOf, nested objects, etc.)'),
    (r'// Lazy init: crea las funciones si Active=True pero a\xfan no existen\.',
     '// Lazy init: creates functions if Active=True but do not exist yet.'),
    (r'// Es una funci\xf3n local',
     '// Is a local function'),
    (r'// Lazy init: si Active=True pero las funciones a\xfan no existen \(ej: Active activado',
     '// Lazy init: if Active=True but functions do not exist yet (e.g. Active activated'),
    (r'// en runtime despu\xe9s de Loaded\), las crea ahora\.',
     '// at runtime after Loaded), creates them now.'),
    (r'// Carga autom\xe1tica de servidores MCP desde archivo JSON \(formato Claude Desktop\)',
     '// Automatic loading of MCP servers from JSON file (Claude Desktop format)'),
    (r'// InitAutoMCP puede llamarse manualmente para forzar la inicializaci\xf3n en runtime\.',
     '// InitAutoMCP can be called manually to force initialization at runtime.'),
    (r'// Propagaci\xf3n autom\xe1tica al cliente real cuando se editan in-place',
     '// Automatic propagation to the real client when edited in-place'),
    (r'// Resuelve la versi\xf3n a usar: si AVersion no est\xe1 vac\xedo la retorna directamente;',
     '// Resolves the version to use: if AVersion is not empty returns it directly;'),
    (r'// si est\xe1 vac\xedo consulta /v1/packages/:name y devuelve la \xfaltima versi\xf3n no-yanked\.',
     '// if empty queries /v1/packages/:name and returns the latest non-yanked version.'),
    (r'// sin extensi\xf3n \(Linux\) en la ra\xedz del ZIP\.',
     '// without extension (Linux) in the ZIP root.'),
    (r'// Retorna \'\' si no se pudo extraer o no se encontr\xf3 el entrypoint\.',
     '// Returns \'\' if could not extract or entrypoint not found.'),
    (r'// Fallback: primer \.exe en Windows, o primer archivo sin extensi\xf3n en Linux',
     '// Fallback: first .exe on Windows, or first file without extension on Linux'),
    (r'// B\xfasqueda recursiva para soportar paquetes con estructura bin/win64/',
     '// Recursive search to support packages with bin/win64/ structure'),
    (r'// Active=True  тЖТ crea las funciones si a\xfan no existen \(lazy\)\.',
     '// Active=True  тЖТ creates functions if they do not exist yet (lazy).'),
    (r'// Fuerza la creaci\xf3n de las 3 funciones internas PPM en runtime\.',
     '// Forces creation of the 3 internal PPM functions at runtime.'),
    (r'// \xdatil si el developer necesita que las funciones existan antes del primer chat',
     '// Useful if the developer needs the functions to exist before the first chat'),
    (r'// Aplicar pol\xedtica Allowed/Blocked antes de mostrar al LLM',
     '// Apply Allowed/Blocked policy before showing to LLM'),
    (r'// Verificar pol\xedtica de whitelist/blacklist',
     '// Check whitelist/blacklist policy'),
    (r'// Si ya est\xe1 registrado: reutilizar salvo que force=true',
     '// If already registered: reuse unless force=true'),
    (r'// TAutoMCPConfig: configuraci\xf3n agrupada del subsistema AutoMCP / PPM\.',
     '// TAutoMCPConfig: grouped configuration of AutoMCP / PPM subsystem.'),
    (r'// Nota: OnAutoMCPRequest se mantiene en TAiFunctions \(pesta\xf1a Events del OI\)\.',
     '// Note: OnAutoMCPRequest remains in TAiFunctions (Events tab of the OI).'),
    (r'// \(resultado de la normalizaci\xf3n en GetTools\)\. Extraemos la parte despu\xe9s del \xfaltimo MCP_TOOL_SEP\.',
     '// (result of normalization in GetTools). Extract the part after the last MCP_TOOL_SEP.'),
    (r'// Si el nombre no coincide con ninguna funci\xf3n conocida, devuelve error con la',
     '// If name does not match any known function, return error with the'),
    (r'// lista de nombres v\xe1lidos para que el LLM los use directamente\.',
     '// list of valid names for the LLM to use directly.'),
    (r'// Si el nombre no se encontr\xf3 y tenemos la lista, devolver error con nombres v\xe1lidos',
     '// If name not found and we have the list, return error with valid names'),
    (r'// fallback: objeto vac\xedo',
     '// fallback: empty object'),
    (r'// Propagar archivos media extra\xeddos al ToolCall \(im\xe1genes, audio, etc\.\)',
     '// Propagate extracted media files to ToolCall (images, audio, etc.)'),
    (r'// Servidores activos: saltar ppm_search y ppm_install; incluir lista exacta de tools con par\xe1metros',
     '// Active servers: skip ppm_search and ppm_install; include exact list of tools with parameters'),
    (r'// Extraer par\xe1metros del inputSchema',
     '// Extract parameters from inputSchema'),
    (r'// Blocked: blacklist de paquetes bloqueados\. Si Allowed est\xe1 vac\xedo, se permite todo excepto estos\.',
     '// Blocked: blacklist of blocked packages. If Allowed is empty, everything is allowed except these.'),
    (r'// Servidores registrados pero proceso a\xfan no iniciado: saltar ppm_search, llamar ppm_install para arrancar',
     '// Registered servers but process not yet started: skip ppm_search, call ppm_install to start'),
    (r'// Eval\xfaa si un paquete puede instalarse seg\xfan la pol\xedtica AutoMCP\.',
     '// Evaluates if a package can be installed according to AutoMCP policy.'),
    (r'// Orden: OnAutoMCPRequest тЖТ Whitelist \(si no vac\xeda\) тЖТ Blacklist тЖТ permitir\.',
     '// Order: OnAutoMCPRequest тЖТ Whitelist (if not empty) тЖТ Blacklist тЖТ allow.'),
    (r'// Vac\xedo = detecta autom\xe1ticamente la ruta por defecto de Claude Desktop seg\xfan el SO\.',
     '// Empty = automatically detects Claude Desktop default path according to OS.'),
    (r'// 1\. Callback din\xe1mico \(m\xe1xima prioridad\)',
     '// 1. Dynamic callback (highest priority)'),
    (r'// AutoLoad: si True, importa ConfigFile autom\xe1ticamente al cargar el componente \(Loaded\)\.',
     '// AutoLoad: if True, imports ConfigFile automatically when component loads (Loaded).'),
    (r'// Divide una l\xednea de argumentos respetando comillas dobles\.',
     '// Splits an argument line respecting double quotes.'),
    (r'// paquetes ya instalados en esta sesi\xf3n',
     '// packages already installed in this session'),
    (r'// Retorna la ruta efectiva del archivo de configuraci\xf3n MCP:',
     '// Returns the effective MCP config file path:'),
    (r'// ConfigFile si est\xe1 asignado, sino <exedir>\\mcp_servers\.json',
     '// ConfigFile if assigned, otherwise <exedir>\\mcp_servers.json'),
    (r'// Registra un stub StdIo sin descargar\. \xdatil si el binario ya est\xe1 instalado\.',
     '// Registers a StdIo stub without downloading. Useful if the binary is already installed.'),
    (r'// Si ya est\xe1 registrado, retornar el existente sin reinstalar',
     '// If already registered, return existing without reinstalling'),
    (r'// Resolver versi\xf3n',
     '// Resolve version'),
    (r'// Determinar directorio de instalaci\xf3n',
     '// Determine installation directory'),
    (r'// Persistir en el archivo de configuraci\xf3n para que AutoLoad lo cargue en la pr\xf3xima sesi\xf3n',
     '// Persist in config file so AutoLoad loads it in next session'),
    (r'// Se llama autom\xe1ticamente desde Loaded si AutoMCP=True\.',
     '// Called automatically from Loaded if AutoMCP=True.'),
    (r'// OnFEnvVarsChanged se dispara autom\xe1ticamente por el OnChange de FEnvVars',
     '// OnFEnvVarsChanged fires automatically from FEnvVars OnChange'),
    (r'// Sobrecarga 2: Recibe la ruta del archivo \(o usa GetEffectiveMCPConfigPath si est\xe1 vac\xeda\)',
     '// Overload 2: Receives the file path (or uses GetEffectiveMCPConfigPath if empty)'),
    (r'// OnFParamsChanged se dispara autom\xe1ticamente por el OnChange de FParams',
     '// OnFParamsChanged fires automatically from FParams OnChange'),
    (r'// AFilePath vac\xedo = usa GetEffectiveMCPConfigPath\.',
     '// AFilePath empty = uses GetEffectiveMCPConfigPath.'),
    (r'// Retorna True si guard\xf3 correctamente\.',
     '// Returns True if saved correctly.'),
    (r'// \xdatil cuando el binario ya est\xe1 instalado manualmente; el llamador debe asignar',
     '// Useful when the binary is already manually installed; the caller must assign'),
    (r'// AVersion vac\xedo = resuelve la \xfaltima versi\xf3n disponible\.',
     '// Empty AVersion = resolves the latest available version.'),
    (r'// AInstallDir vac\xedo = ~/\.ppm/mcp/<AName>/',
     '// Empty AInstallDir = ~/.ppm/mcp/<AName>/'),
    (r'// AutoMCPConfig: configuraci\xf3n agrupada del subsistema AutoMCP / PPM\.',
     '// AutoMCPConfig: grouped configuration of AutoMCP / PPM subsystem.'),
    (r'// OnAutoMCPRequest: callback din\xe1mico para aprobar/denegar instalaciones en runtime\.',
     '// OnAutoMCPRequest: dynamic callback to approve/deny installations at runtime.'),
    (r'// Preferir RawSchemaJson \(schema completo\) sobre la reconstrucci\xf3n desde TFunctionParamsItems',
     '// Prefer RawSchemaJson (complete schema) over reconstruction from TFunctionParamsItems'),
    (r'// Se compara contra el primer token del comando, sin distinguir may\xfasculas\.',
     '// Compares against the first command token, case-insensitive.'),
    (r'// Evento disparado cuando un comando es rechazado por la pol\xedtica de seguridad\.',
     '// Event fired when a command is rejected by the security policy.'),
    (r'// Verificar si el primer token est\xe1 en la lista',
     '// Check if the first token is in the list'),
    (r'// Evento disparado cuando un comando es bloqueado por la pol\xedtica de seguridad\.',
     '// Event fired when a command is blocked by the security policy.'),
    (r'// Devuelve \'\' si el comando est\xe1 permitido, o un mensaje de error si est\xe1 bloqueado\.',
     '// Returns \'\' if the command is allowed, or an error message if blocked.'),
    (r'// Acceso v\xeda RTTI al nombre publicado de TAiToolBase',
     '// Access via RTTI to the published name of TAiToolBase'),
    (r'// Intentamos leer la propiedad Description v\xeda RTTI si existe',
     '// Try to read the Description property via RTTI if exists'),
    (r'// Llama Execute v\xeda RTTI \(firma: Execute\(ANode, AInput, var AOutput\)\)',
     '// Calls Execute via RTTI (signature: Execute(ANode, AInput, var AOutput))'),
    (r'// Retorna el JSON Schema de par\xe1metros\. NO liberar\.',
     '// Returns the JSON Schema of parameters. Do NOT free.'),
    (r'// Indica si la herramienta est\xe1 disponible para su uso\.',
     '// Indicates if the tool is available for use.'),
    (r'// Captura errores del LLM para re-lanzarlos como excepci\xf3n en DoExecute\.',
     '// Captures LLM errors to re-throw them as exception in DoExecute.'),
    (r'// TAiChatConnection invoca este m\xe9todo cuando el modelo pide ejecutar',
     '// TAiChatConnection invokes this method when the model requests to execute'),
    (r'// una funci\xf3n\. Buscamos la herramienta en el registry y ejecutamos\.',
     '// a function. We look for the tool in the registry and execute.'),
    (r'// Punto de entrada principal del nodo\. Reemplaza el DoExecute gen\xe9rico\.',
     '// Main entry point of the node. Replaces the generic DoExecute.'),
    (r'// Determinar the active registry for this ejecuci\xf3n',
     '// Determine the active registry for this execution'),
    (r'// Par\xe1metros v\xeda TStrings \(Asynchronous DEBE ser False en nodos de agente\)',
     '// Parameters via TStrings (Asynchronous MUST be False in agent nodes)'),
    (r'// Limpiar ModelCaps/SessionCaps: LLMNode usa s\xf3lo TAiFunctions\.',
     '// Clear ModelCaps/SessionCaps: LLMNode uses only TAiFunctions.'),
    (r'// Sin esto, el driver puede a\xf1adir tools built-in \(web_search,',
     '// Without this, the driver may add built-in tools (web_search,'),
    (r'// code_execution, etc\.\) que nuestro c\xf3digo no sabe manejar\.',
     '// code_execution, etc.) that our code does not know how to handle.'),
    (r'// Tool_Active debe ser True para que the driver env\xede las tools al LLM\.',
     '// Tool_Active must be True for the driver to send the tools to the LLM.'),
    (r'// Ejecutar el input del nodo \(el loop de tools es autom\xe1tico\)',
     '// Execute the node input (the tools loop is automatic)'),
    (r'// Si el LLM report\xf3 un error y la respuesta est\xe1 vac\xeda, propagarlo',
     '// If the LLM reported an error and the response is empty, propagate it'),
    (r'// TLLMNode extiende TAIAgentsNode a\xf1adiendo un modelo LLM con capacidad de',
     '// TLLMNode extends TAIAgentsNode by adding an LLM model with capacity to'),
    (r'// llamar herramientas del TAiToolRegistry autom\xe1ticamente\. El loop LLM тЖТ',
     '// call tools from TAiToolRegistry automatically. The LLM тЖТ'),
    (r'// Tool тЖТ Observaci\xf3n es manejado internamente por TAiChatConnection',
     '// Tool тЖТ Observation is handled internally by TAiChatConnection'),
    (r'// Estado temporal v\xe1lido s\xf3lo durante DoExecute \(un hilo a la vez por nodo\)',
     '// Temporary state valid only during DoExecute (one thread at a time per node)'),
    (r'// Captura el \xfaltimo error del LLM para re-lanzarlo como excepci\xf3n',
     '// Captures the last LLM error to re-throw it as exception'),
    (r'// Modelo espec\xedfico del proveedor \(vac\xedo = usa el default del driver\)',
     '// Provider-specific model (empty = uses driver default)'),
    (r'// API key\. Soporta sintaxis @ENV_VAR_NAME para resoluci\xf3n en runtime\.',
     '// API key. Supports @ENV_VAR_NAME syntax for runtime resolution.'),
    (r'// Instrucci\xf3n de sistema para el LLM',
     '// System instruction for the LLM'),
    (r'// M\xe1ximo de tokens en la respuesta \(0 = usa el default del driver\)',
     '// Maximum tokens in response (0 = uses driver default)'),
    (r'// Si True, inyecta autom\xe1ticamente todas las herramientas disponibles del registry',
     '// If True, automatically injects all available tools from the registry'),
    (r'// 1\. Construir el cuerpo de la petici\xf3n JSON',
     '// 1. Build the JSON request body'),
    (r'// La API espera un array de textos\. Creamos uno con el \xfanico input\.',
     '// The API expects an array of texts. We create one with the single input.'),
    (r'// Lo a\xf1adimos si es un valor v\xe1lido para Cohere\.',
     '// Add it if it is a valid value for Cohere.'),
    (r'// Opcional: Lanzar un warning o un error si el usuario especifica una dimensi\xf3n',
     '// Optional: Throw a warning or error if user specifies a dimension'),
    (r'// que no es v\xe1lida para este modelo, para evitar confusiones\.',
     '// that is not valid for this model, to avoid confusion.'),
    (r'// 2\. Pasar el objeto JSON parseado directamente al m\xe9todo de parseo\.',
     '// 2. Pass the parsed JSON object directly to the parse method.'),
    (r'// Driver de embeddings gen\xe9rico para cualquier endpoint compatible con la API',
     '// Generic embeddings driver for any API-compatible endpoint'),
    (r'// Uso m\xednimo:',
     '// Minimal usage:'),
    (r'// Driver gen\xe9rico para cualquier API de embeddings compatible con OpenAI\.',
     '// Generic driver for any OpenAI-compatible embeddings API.'),
    (r'// Configura Url, ApiKey y Model en tiempo de dise\xf1o o en c\xf3digo\.',
     '// Configure Url, ApiKey and Model at design time or in code.'),
    (r'// gen\xe9ricos simult\xe1neos en el mismo proyecto\.',
     '// simultaneous generics in the same project.'),
    (r'// Permite usar m\xfaltiples instancias apuntando a APIs distintas\.',
     '// Allows using multiple instances pointing to different APIs.'),
    (r'// Campos est\xe1ndar OpenAI-compatible',
     '// Standard OpenAI-compatible fields'),
    (r'// Formato 1 тАФ OpenAI est\xe1ndar: \{"data": \[\{"embedding": \[\.\.\.\]\}\]\}',
     '// Format 1 тАФ Standard OpenAI: {"data": [{"embedding": [...]}]}'),
    (r'// Vector\[1024\]    //Esta es la mejor versi\xf3n a mayo/2024',
     '// Vector[1024]    //This is the best version as of May/2024'),
    # Single Spanish word/phrase replacements in comments (less specific, apply last)
    (r'// aqu\xed', '// here'),
    (r'// acci\xf3n', '// action'),
    (r'// a\xfan', '// still'),
    (r'// b\xe1sico', '// basic'),
    (r'// b\xfasqueda', '// search'),
    (r'// c\xf3digo', '// code'),
    (r'// car\xe1cter', '// character'),
    (r'// configuraci\xf3n', '// configuration'),
    (r'// conexi\xf3n', '// connection'),
    (r'// creaci\xf3n', '// creation'),
    (r'// descripci\xf3n', '// description'),
    (r'// direcci\xf3n', '// address'),
    (r'// ejecuci\xf3n', '// execution'),
    (r'// emisi\xf3n', '// emission'),
    (r'// est\xe1ndar', '// standard'),
    (r'// extracci\xf3n', '// extraction'),
    (r'// funci\xf3n', '// function'),
    (r'// gesti\xf3n', '// management'),
    (r'// im\xe1genes', '// images'),
    (r'// \xedndice', '// index'),
    (r'// \xedndices', '// indices'),
    (r'// inicializaci\xf3n', '// initialization'),
    (r'// instrucci\xf3n', '// instruction'),
    (r'// interfaz', '// interface'),
    (r'// m\xe1ximo', '// maximum'),
    (r'// m\xe9todo', '// method'),
    (r'// m\xf3dulo', '// module'),
    (r'// n\xfamero', '// number'),
    (r'// operaci\xf3n', '// operation'),
    (r'// opci\xf3n', '// option'),
    (r'// par\xe1metro', '// parameter'),
    (r'// par\xe1metros', '// parameters'),
    (r'// petici\xf3n', '// request'),
    (r'// p\xe1gina', '// page'),
    (r'// raz\xf3n', '// reason'),
    (r'// respuesta', '// response'),
    (r'// secci\xf3n', '// section'),
    (r'// sesi\xf3n', '// session'),
    (r'// sistema', '// system'),
    (r'// transmisi\xf3n', '// transmission'),
    (r'// \xfaltimo', '// last'),
    (r'// \xfanico', '// unique'),
    (r'// \xfatil', '// useful'),
    (r'// vac\xedo', '// empty'),
    (r'// v\xe1lido', '// valid'),
    (r'// versi\xf3n', '// version'),
    (r'// v\xeda', '// via'),
    (r'// \xe9xito', '// success'),
    (r'// \xf3rden', '// order'),
    (r'// aqu\xed', '// here'),
    (r'// all\xed', '// there'),
    (r'// autom\xe1ticamente', '// automatically'),
    (r'// autom\xe1tico', '// automatic'),
    (r'// disponible', '// available'),
    (r'// espec\xedfico', '// specific'),
    (r'// expl\xedcito', '// explicit'),
    (r'// gen\xe9rico', '// generic'),
    (r'// l\xf3gica', '// logic'),
    (r'// l\xf3gico', '// logical'),
    (r'// m\xednimo', '// minimum'),
    (r'// p\xfablico', '// public'),
    (r'// r\xe1pido', '// fast'),
    (r'// tambi\xe9n', '// also'),
    (r'// t\xe9cnico', '// technical'),
    (r'// \xfanica', '// only/unique'),
    (r'// \xfaltima', '// last'),
    (r'// \xfaltimas', '// last'),
    (r'// \xfaltimos', '// last'),
    (r'// \xfaltimas', '// last'),
    (r'// aqu\xed', '// here'),
    (r'// despu\xe9s', '// after'),
    (r'// aqu\xed', '// here'),
    (r'// all\xed', '// there'),
    (r'// a\xf1ade', '// adds'),
    (r'// a\xf1adir', '// add'),
    (r'// a\xf1adido', '// added'),
    (r'// a\xf1adimos', '// we add'),
    (r'// a\xf1adimos', '// add'),
    (r'// aqu\xed', '// here'),
    (r'// aqu\xed', '// here'),
    (r'// aqu\xed', '// here'),
    (r'// aqu\xed', '// here'),
    (r'// aqu\xed', '// here'),
]

def translate_comment(line):
    """Apply all translations to a single line."""
    result = line
    for pattern, replacement in translations:
        try:
            new_result = re.sub(pattern, replacement, result, flags=re.IGNORECASE)
            if new_result != result:
                result = new_result
        except re.error:
            # Skip invalid regex patterns
            pass
    return result

modified_count = 0
translated_lines = 0
modified_files = []

for root, dirs, files in os.walk(source_dir):
    for fname in files:
        if not fname.endswith('.pas'):
            continue
        filepath = os.path.join(root, fname)
        try:
            with open(filepath, 'r', encoding='utf-8-sig') as f:
                content = f.read()
        except:
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
            except:
                continue

        original = content
        lines = content.split('\n')
        new_lines = []
        file_changed = False
        file_translated = 0

        for line in lines:
            # Only process lines with // comments that contain Spanish accented chars
            if '//' in line and re.search(r'[áéíóúüñÁÉÍÓÚÜÑ]', line):
                new_line = translate_comment(line)
                if new_line != line:
                    file_translated += 1
                    file_changed = True
                new_lines.append(new_line)
            else:
                new_lines.append(line)

        if file_changed:
            new_content = '\n'.join(new_lines)
            # Preserve original line endings
            if '\r\n' in original:
                new_content = new_content.replace('\n', '\r\n')
            with open(filepath, 'w', encoding='utf-8', newline='') as f:
                f.write(new_content)
            modified_count += 1
            translated_lines += file_translated
            modified_files.append(os.path.relpath(filepath, source_dir))

print(f"=== Translation Summary ===")
print(f"Files modified: {modified_count}")
print(f"Comment lines translated: {translated_lines}")
print()
print("Files changed:")
for f in sorted(modified_files):
    print(f"  {f}")
